radiasoft/sirepo

sirepo/package_data/static/js/sirepo-plotting.js, sirepo/template/srw.py
Hi Paul,
I implemented the fix for https://github.com/radiasoft/sirepo/issues/84, please review it and merge in case everything is fine.
Due to the units can be quite long, it's desirable if the added ordinate values are displayed on a new line, but I haven't found how to do it easily (tried `.html()` with `<br>` tag inside instead of `.text()`, but it didn't help). Maybe you can suggest better way to do it?
Thanks,
Maksim
=> Fix for https://github.com/radiasoft/sirepo/issues/84.

sirepo/pkcli/service.py, sirepo/server.py
I think this fix is fine, but it could break cookies so I want to make sure I get it right. I want to get rid of [formatted values](https://github.com/radiasoft/pykern/commit/3b9be7133ea7b2ae884b41507e481e7dcacc1707#diff-6a7e51d1079ccbc0ababe499d109774a) in pkconfig. I wanted to be able to parse a value as JSON, and that conflicts with the formatting syntax. I don't think it is that valuable of a feature. And is easy enough to work around.
=> pkconfig formatted values going away

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/json/elegant-schema.json, sirepo/package_data/static/json/hellweg-schema.json, sirepo/package_data/static/json/schema-common.json, sirepo/package_data/static/json/shadow-schema.json, sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/static/json/warppba-schema.json, sirepo/package_data/static/json/warpvnd-schema.json, sirepo/simulation_db.py
Notes:
Adding UI for simulation-wide defaults turns out to be a heavy task, as per @moellep - it requires a new mechanism to store data outside the simulation folder structure. That could prove useful for other things as well, but was outside the scope of this issue.
I added a 'commonEnums' object to schema-common.json, and put the various color map names in there. Might be a good home for Boolean etc.
The color map applied to a plot is the first one found in 1) the stored model data 2) the default for that report (in the schema) 3) the app-level default as stored in SIREPO.PLOTTING_COLOR_MAP (in the javascript) and 4) a global default SIREPO.DEFAULT_COLOR_MAP (which is currently 'viridis').
Since the reports for srw are pretty complex, I opted to put the color map menu in its own tab, …
=> Added per-report color map for 3d plots, pursuant to Issue #706

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/js/sirepo-beamline.js, sirepo/package_data/static/js/sirepo-components.js
I added @moellep 's suggestions and got rid of the timeout. However:
Angular hates checkboxes in particular, so I use ng-open (irrelevant to checkboxes) to keep the value updated as it changes in the background. A one-time initialization fails in a couple of cases that this trick handles.
I also added a couple of cosmetic changes to the beamline: a close "x" at the top of the item editor and fixing the position label so 0 displays as "0m", not a warning symbol.
=> Bootstrap toggle fixes for Issues #936 and #950 and settings menu fix for Issue #892

sirepo/package_data/static/css/landing-page.css, sirepo/package_data/static/html/landing-page-home.html, sirepo/package_data/static/html/landing-page-srw.html, sirepo/package_data/static/html/simulations.html, sirepo/package_data/static/html/sr-landing-page.html, sirepo/package_data/static/js/elegant.js, sirepo/package_data/static/js/hellweg.js, sirepo/package_data/static/js/landing-page.js, sirepo/package_data/static/js/shadow.js, sirepo/package_data/static/js/sirepo-beamline.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/js/warppba.js, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/json/elegant-schema.json, sirepo/template/srw.py
Notes:
#76: As requested, the subtitle handling now lives in srw.py (`extract_report_data`). The "characteristic" subtitle pertains to initialIntensityReport, sourceIntensityReport, or any watchpointReport
#1044: Went from passively renaming beamlines and elements to actively rejecting names already in use. To this end, I added a validation service for general handling of field validation - the `validateFieldOfType` now lives there instead of the utilities service.  The SafePath directive could eventually use it as well
#1055: The RadiaSoft "spinner" and a "Creating <name>..." message appears at the end of the simulations (icons or list)
#1056: I opted for a tab interface to select the Demo and Expert modes; radio buttons, switches, and double launch buttons seemed clunky to me, and tabs …
=> Fixes for Issues #76, #1044, #1055, #1056

sirepo/package_data/static/js/sirepo-beamline.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/json/srw-schema.json, sirepo/template/srw.py
Notes:
#1059: The driving conflict was between the DOM transform performed by ngDraggable and the d3 transform.  Resolved by resetting the former when drag completes.  This fix also keeps the popup in place during zoom
#1120: This toggle is set only in the initial intensity report, in a primary/replica arrangement.  Users can still change the characteristic for each watchpoint but that does not currently turn off the toggle, so they will be reset to match the initial report should it be run agan
=> Popup report drag fixes (#1059), characteristic copying to watchpoints (#1120), script download in options menu (#1160) 

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/html/plot2d.html, sirepo/package_data/static/html/plot3d.html, sirepo/package_data/static/html/simulations.html, sirepo/package_data/static/js/ext/ngDraggable.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/schema-common.json, sirepo/server.py
Notes:
#1154: Keyboard manipulation of focus points no longer requires the cursor to be over the plot in question. This comes with other features:
- Multiple plots can be be active, though only one at a time can process input
- The plot currently processing input is highlighted
- Deactivating the the current plot (by mouse or ESC) automatically moves input to the next plot, if any
- Users can TAB between active plots to change which one moves its focus points
- When input fields (for numbers etc.) receive focus they take over receiving the keyboard input if any plots are active.  The plots regain processing after input fields lose focus
#990: Users can no longer create new or move existing simulations or folders inside example folders.  Note that:
- Example folders and simulations in icon …
=> Focus point keyboard input and example folders

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/js/ext/canvg.js, sirepo/package_data/static/js/sirepo-beamline.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/sirepo.js
Notes:
#1148: Users can make reports fullscreen with a button in the panel header using the built-in javascript API.  The 3rd-party canvg.js file required some modification since it freaks out on a lot of the CSS required to handle multiple browsers.  Other items of interest:
- The fullscreen button is disabled when the report is collapsed
- Reports cannot be edited or collapsed when in fullscreen, but animations and simulations can be run
- Popup reports are not scaled yet
#1155: Two parts to this one:
- First, when a new watchpoint was created, it was evaluated as soon as it initialized. However, the simulation is also saved at the same moment, after which each WP gets evaluated.  When the new WP runs depends on the timing of the save, making it essentially random. We now avoid …
=> Fullscreen reports (#1148) and watchpoint evaluation order (#1155)

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-lattice.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/json/srw-schema.json
Notes:
#1148: To address plots not fully displayed in fullscreen, added call to ``refresh()`` in listeners;  needed an additional soupçon of margin to get Safari to work.  Also improved fullscreen for the elegant beamline/lattice
#1201: Split the Geometry tab into Main, Material, Geometry, and Polarizability, based on what seems to belong together, with the idea that we can hone it based on user feedback
=> SRW crystal properties (#1201), fullscreen tweaks (#1148)

sirepo/package_data/static/html/index.html, sirepo/package_data/static/js/rs4pi.js, sirepo/package_data/static/js/sirepo-plotting-vtk.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/json/elegant-schema.json, sirepo/package_data/static/json/hellweg-schema.json, sirepo/package_data/static/json/jspec-schema.json, sirepo/package_data/static/json/myapp-schema.json, sirepo/package_data/static/json/rs4pi-schema.json, sirepo/package_data/static/json/schema-common.json, sirepo/package_data/static/json/shadow-schema.json, sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/static/json/synergia-schema.json, sirepo/package_data/static/json/warppba-schema.json, sirepo/package_data/static/json/warpvnd-schema.json, sirepo/server.py, sirepo/simulation_db.py, sirepo/util.py
Notes:
- ```schema-common``` and the app schemae now list out "dynamicFiles" and "staticFiles" that refer only to the file name.  Static files are loaded by ```index.html``` with jinja loops, while dynamic files get loaded by sirepo.  Most ```<script>``` tags have been removed.  Consequently, each app's javascript is now referenced in its schema and dynamically loaded
- Files are grouped into "local" and "external" which map to directories
- Also in ```schema-common```,  things like "commonModels" have been moved under a single "common" section and named the same as in the app schema (so just "model").  The idea is to eventually loop over them to merge
- The schema fetch and validation in ```simulation_db``` use ``` pkcollections.Dict``` and dot syntax
- ```merge_dicts``` now allows …
=> More dynamic (and now static) loading of files (#1299) plus #1330

sirepo/package_data/static/html/landing-page-jspec.html, sirepo/package_data/static/js/jspec.js
Link changed to https://github.com/zhanghe9704/electroncooling/blob/master/JSPEC%20User%20manual.md suggested by @robnagler
=> Fix broken link for JSPEC manual in landing page.

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-plotting.js
Notes:
- Popup reports print the x coordinate only once, instead of repeating it for each plot
- The popup window sizes to fit in both dimensions
- Popup text wraps if the window would otherwise extend beyond the plot boundaries
- If a unit is inverse (e.g. "1/s"), it gets converted to e.g. "unit-1" in the popup window, so the "1" does not look like part of the numeric value
=> Popup report changes for #1434, #1437

sirepo/package_data/static/js/sirepo-components.js
Notes:
The page would intermittently stay in modal mode (forbidding interaction) after the copy from the simulation's settings menu was complete.  @moellep traced this to a probable race condition between hiding the dialog and removing it upon destruction.  We now add the dialog node to the 'ng-view' node instead of the body, so it gets wiped when the new page is loaded, obviating the need to remove it explicitly.  That should make it behave the same as copying from the simulations list
=> Fixed bug introduced by previous fix of #1477

container-runner-requirements.txt, sirepo/pkcli/service.py, sirepo/runner/__init__.py, sirepo/runner/container.py
**(Messy prototype, posting for discussion only, do not merge.)**
Here's a first draft of container runner functionality. It can
successfully run 'myapp', while routing everything through docker,
including cancellation.
In terms of scope, I think it currently covers everything in the SOW1
milestone, except that it doesn't use TLS to connect to docker,
doesn't do multi-host slot management, and has no automated tests.
There's definitely enough to start discussing though :-).
In order to get something working quickly, this uses a hybrid model,
with threads and classic blocking libraries (redis-py, docker-py) on
one hand, plus Trio to manage the threads, and a bit of glue to
integrate the threads into Trio's cancellation system (so e.g.
control-C works cleanly). This involves a small amount …
=> [WIP] Container runner

sirepo/simulation_db.py, sirepo/srschema.py
WIP #1562 - this addresses only the schema attributes mentioned in the issue -- other cases will be handled in subsequent PRs
Notes:
- schema.py has been renamed to srschema.py to parallel other module names and avoid conflict with the many references to ```schema``` objects
=> Python refactor import schema

setup.py, sirepo/package_data/static/html/webcon-analysis.html, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/webcon.js, sirepo/package_data/static/json/webcon-schema.json, sirepo/pkcli/webcon.py, sirepo/template/template_common.py, sirepo/template/webcon.py
This adds fitting data to a user-specified curve parsed by the ```sympy``` package.
Notes:
- Currently assumes the data to be fit is in order along the "x" axis
- Displays 2-standard-deviation (95%) confidence bands
- As part of the above, introduces the concept of "parent/child" plots.  Children have an attribute ```_parent``` whose value is the label of another plot, though we can use a name or id or whatever.  Child plots share the color and visibility of their parents
=> Curve fitting #1555

sirepo/srdb.py
When running sirepo in a fresh Docker container on the beta channel, the following problem is observed:
```py
[py2; /]$ sirepo service http
Traceback (most recent call last):
File "/home/vagrant/.pyenv/versions/py2/bin/sirepo", line 10, in <module>
sys.exit(main())
File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/sirepo_console.py", line 18, in main
return pkcli.main('sirepo')
File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/pykern/pkcli/__init__.py", line 98, in main
argh.dispatch(parser, argv=argv)
File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
for line in lines:
File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/ar …
```
=> FIX: misspelled attribute name "py_pth"

sirepo/package_data/static/html/webcon-controls.html, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/webcon.js, sirepo/package_data/static/json/webcon-schema.json, sirepo/pkcli/webcon.py, sirepo/template/template_common.py, sirepo/template/webcon.py
Notes:
- The corrector setting, beam position, and BPM plots are reports rather than animations, for now. They don't update quite right yet so refreshing the page or making a change to model data is sometimes required
- In general, position is indicated by color, x/horizontal values with a square, y/vertical values with a triangle, and data further back in time with decreasing alpha. The beam position plot is a little different since there is no way yet to individually color the segments of a single path
- Parameter plotting now allows each sub-plot to have its own x values, rather than using the same x for every set of y values
- The beam position and corrector plots allow the user to select a time range and sample period to reduce clutter.  Time is relative to when the user connects to …
=> Webcon epics plots

sirepo/package_data/static/js/sirepo-plotting.js, sirepo/template/webcon.py
Notes:
- Changed label to frequency from angular frequency
- The x units are now "1/s".  Note that normally we re-label the x-axis of plots as we zoom in to keep the tick values between 1-10 or so, but this is confusing with things like inverse units (that's why the units were "s-1" - the label would otherwise change to e.g. "m1/s").  The solution here is to preserve the scale of the axis regardless of zoom level
- y values normalized to the largest peak
=> Webcon fft fixup

sirepo/package_data/static/js/webcon.js, sirepo/package_data/static/json/webcon-schema.json, sirepo/template/webcon.py
Notes:
- Allows user to have the variables and parameters get filled in as they enter the equation
- We assume that variables will be among the usual suspects (x, y, z, t)
- The schema defines a handful of allowed functions and symbols (trig stuff, exp, log, abs, pi). Other needed items can be added
- Anything not a variable or function is treated as a parameter
- Variables and params are allowed only one alphabetic character for now
- The server does similar validations before handing the equation off to sympy.  That should reduce the ```eval()``` mischief, but merits scrutiny
=> Webcon fit auto-fill and security

sirepo/package_data/static/html/conductor-grid.html, sirepo/package_data/static/html/warpvnd-source.html, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/json/warpvnd-schema.json, sirepo/package_data/template/warpvnd/base.py.jinja, sirepo/package_data/template/warpvnd/source-field.py.jinja, sirepo/pkcli/warpvnd.py, sirepo/template/template_common.py, sirepo/template/warpvnd.py
Notes:
- This replaces the field and field comparison reports with "animations" so that the reports dip from the same simulations results (addressing #1739 ). This is for both 2d and 3d at the moment, as allowing two different report types depending on that was getting a little convoluted
- Consider this a starting point for moving from the historical report/animation duality to a unified approach (again see the discussion for #1739). I've gone with "calculation" or "calc" as a possible description distinct from "simulation"
- 3d conductor grid now has carats in the bottom plot
- Field comparison report allows selection of the y component of the field in 3d
- Heatmaps allow for optional min/max to set the range of values.  Useful for cross-sections that are uniform but vary along the …
=> Fete 3d animation

sirepo/package_data/static/html/conductor-grid.html, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/template/warpvnd/base.py.jinja
Notes:
- #1742: was adding 0-volt conductors which the previous code did not.  Removed that
- #1743: changes to support stl files introduced a constant 1e-6 factor to conductor sizes, which should not matter except vtk balks at very small numbers.  Defaulting to 1 instead gets vtk to behave
=> Minor fixes to fete 3d

sirepo/package_data/template/warpvnd/base.py.jinja, sirepo/package_data/template/warpvnd/impact-density.py.jinja
Note that impact density on the planes takes a while when divided into many cells, which can conflict with the cell density desired for field calculations
=> Fixed scale bug, removed impact density for stl

sirepo/package_data/static/en/landing.html, sirepo/package_data/static/en/particle-accelerators.html, sirepo/package_data/static/en/xray-beamlines.html
Note that those intermediate landing pages are no longer reachable (but not deleted)
=> Landing page code links

sirepo/package_data/static/html/particle3d.html, sirepo/package_data/static/html/warpvnd-visualization.html, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/json/warpvnd-schema.json, sirepo/template/warpvnd.py
The main thrust of this PR is to copy the axis and slice features of the field report to the field animation and use a full 3d field to color particle traces
Notes:
- Added axes and slice to electric field views (was just potential (phi))
- Unlike the field report, the field animation has the slice slider in the editor. This to have a fixed set of parameters while the animation runs
- The particle data now includes the full 3d field rather than borrowing the 2d from the field animation
- After experimentation around interpolating the field, it seems replacing all that with a simple average at the points in a particle trace is good enough.  I opted against implementing Bresenham's line algorithm plus an average weighted by the fraction of the line in each cell so derived
Other misc items: …
=> Fete visualization changes

sirepo/api_auth.py, sirepo/auth/__init__.py, sirepo/auth/email.py, sirepo/auth/github.py, sirepo/auth/guest.py, sirepo/github_srunit.py, sirepo/http_reply.py, sirepo/package_data/static/html/complete-registration.html, sirepo/package_data/static/html/login-with-email-confirm.html, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/schema-common.json, sirepo/pkcli/job_process.py, sirepo/server.py, sirepo/srunit.py, sirepo/uri.py, sirepo/uri_router.py, sirepo/util.py, tests/auth/email_test.py, tests/auth/github_test.py, tests/auth/guest_deprecated_test.py, tests/auth/guest_test.py, tests/auth_test.py
* Fix #2011 All redirects now go through javascript-redirect.html
* Fix #2010 Local redirect defaults to correct route
* Added sirepo.util.SRException and Redirect (base is Reply)
* http_reply.gen_sr_exception and gen_user_alert have been replaced by gen_exception
* uri_router.call_api catches these exceptions and converts to responses
* Factored out sirepo.uri from http_reply and uri_router
* srunit now supports redirects properly (redirect=True by default)
=> Fix #1987 Confirmation page for emailed link

sirepo/job_driver/__init__.py, sirepo/job_driver/local.py, sirepo/job_driver/sbatch.py
Driver's persist for the life of the system so they should never be removed from
instances. In the event that the websocket connection is broken with the agent
(ex agent dies unexpectedly) there is no reason to remove self from
instances. The agent will be re-started on the next request.
=> Do not delete self from instances.

sirepo/mpi.py, sirepo/pkcli/elegant.py, sirepo/pkcli/flash.py, sirepo/pkcli/hellweg.py, sirepo/pkcli/jspec.py, sirepo/pkcli/myapp.py, sirepo/pkcli/opal.py, sirepo/pkcli/rcscon.py, sirepo/pkcli/rs4pi.py, sirepo/pkcli/shadow.py, sirepo/pkcli/srw.py, sirepo/pkcli/synergia.py, sirepo/pkcli/warppba.py, sirepo/pkcli/warpvnd.py, sirepo/pkcli/webcon.py, sirepo/pkcli/zgoubi.py, sirepo/template/template_common.py
save_chdir is unnecessary for pkcli codes since job_cmd
executes in the run_dir.
exec(PARAMETERS_PYTHON_FILE) is now template_common.exec_parameters
and exec_parameters_with_mpi.
Also cleaned up pkcli.warppba step loops
=> Fix #2350 removed save_chdir and factored out exec()

sirepo/job_driver/__init__.py, sirepo/job_driver/sbatch.py, sirepo/job_supervisor.py
Sbatch resources are not ours to manage therefore ops sent to
sbatch don't need to be timed.
=> Fix #2484. All sbatch ops are untimed.

sirepo/job_api.py, sirepo/job_driver/__init__.py, sirepo/package_data/static/html/flash-physics.html, sirepo/package_data/static/html/flash-source.html, sirepo/package_data/static/html/flash-visualization.html, sirepo/package_data/static/json/flash-schema.json, sirepo/package_data/template/flash/default-data.json, sirepo/package_data/template/flash/examples/caplaserbella.json, sirepo/package_data/template/flash/examples/rtflame.json, sirepo/pkcli/admin.py, sirepo/pkcli/flash.py, sirepo/sim_data/__init__.py, sirepo/sim_data/flash.py, sirepo/template/flash.py, tests/pkcli/roles_test.py
The rpm is symlinked to the simulation_lib_dir and is lazily
loaded when flash is run. It will only be unpakced one time
for the life of an agent.
=> Fix to handle FLASH distributed as an rpm not a zip.

sirepo/job_supervisor.py, sirepo/srtime.py, sirepo/srunit.py, tests/supervisor_purge_free_sims_test.py
There are a few fixes:
1. In __db_init we use prev_db to get the jobRunMode.
2. When a run_dir is purged we initiliaze a new supervisor db.
Previously we didn't initialize a new db so the gui thought
there were frames available and requested them resulting in
"Report not generated." Initializing the db solves this by
re-initializing parallelStatus so the frameCount is 0 and no frames
are requested.
3. If a job status is in job_run_purged we need to add it to the
purged_jids_cache. Without this we read the db file for purged jobs
each time purge_free_simulations() runs.
=> Fix #2518. Deleted run dirs do not result in an error.

sirepo/job_driver/sbatch.py, sirepo/package_data/static/js/sirepo-components.js
When NERSC is down for maintenance a ProtocolError is raised.
We now catch it and let the user know that we were unable to
connect. In addition, the modal now disappears when there is an
error so the user can see the alert text.
=> Fix #2527. Better error when NERSC is down.

sirepo/job_api.py, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/radia-schema.json, sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/static/json/warppba-schema.json, sirepo/pkcli/job_agent.py
Users can now enter a NERSC repo and it will be used for running
the job. The field is optional. If no repo is supplied then one
won't be supplied to sbatch and the default repo for the user
will be used.
I'd like to test this before merging. Cori is down right now but when it is back up and we sort out networking issues with the VM on our server I will.
=> Fix #2501. Allow NERSC project/repo selection.

sirepo/status.py
This just give a better error message when runSimulation results in an error.
=> Fix radiasoft/ops#509. runSimulation can result in an error.

sirepo/package_data/template/srw/parameters.py.jinja
Abort mpi if extract fails
communicate zip file via bcast
If too many files, also raise exception
=> Fix #2537 protect zip extract in mpi4py

sirepo/auth/__init__.py, sirepo/auth_db.py, sirepo/job_api.py, sirepo/job_supervisor.py
Removed direct calls to auth_db.init
made init() private and call
reduced race condition time in _migrate_db_file()
We can mitigate race condition by starting sirepo
without starting job_supervisor. This would be normal
for older installations.
=> Fix #2592 auth_db init at module level

sirepo/auth/__init__.py, sirepo/auth_db.py, sirepo/job_supervisor.py
This partially reverts pulls/2594. In that pull we moved
auth_db.init() to the module level and the auth_db was initialized on
import. This caused agents to init the db which they don't have access
to. This reverts part of that pull so auth_db.init() is called by
those who need it initialized.
=> Fix #2606. Control when auth_db is initialized.

sirepo/sim_data/flash.py
In f4c83274144d1de2b8868f3a33d2e4bf952acb46 CapLaser was renamed to
CapLaserBELLA. A fixup was not created to change the flashType.
This creates the fixup.
=> Fix radiasoft/sirepoflash#12. Update existing CapLaserBELLA simulations.

sirepo/job_driver/__init__.py, sirepo/job_driver/docker.py, sirepo/job_driver/sbatch.py, sirepo/job_supervisor.py, sirepo/pkcli/job_agent.py, sirepo/pkcli/test_http.py, sirepo/tornado.py, sirepo/util.py, tests/cancel_delay_test.py, tests/job_concurrency1_test.py
runCancel takes snapshot of queue before doing anything,
and then intersects that with the list of current ops
at the time it starts to cancel. This avoids canceling
ops "in the future".
In myapp, setting favoriteTreat to agent_start_delay=N where
N is a number of seconds will cause agent to sleep for N seconds
before sending OP_LIVE.
=> Fix #2650 only cancel ops already in queue

sirepo/auth/__init__.py, sirepo/html.py, sirepo/http_reply.py, sirepo/package_data/static/html/synergia-visualization.html, sirepo/package_data/static/html/zgoubi-visualization.html, sirepo/server.py
The template syntax looks like:
```txt
<div class="row">
sim_settings_and_status(scope=visualization);
<div class="col-md-6 col-xl-4" data-ng-if="visualization.simState.hasFrames()">
```
We could make it recursive and nested. Not important right now. I want to explore how we could simplify the html templates, and then the inline templates in the js.
=> WIP #2691 html.render: non-jinja templating

sirepo/job_driver/__init__.py, sirepo/job_driver/docker.py, sirepo/job_driver/sbatch.py, sirepo/job_supervisor.py, sirepo/package_data/static/html/elegant-visualization.html, sirepo/package_data/static/html/warpvnd-visualization.html, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/srw.js, sirepo/pkcli/test_http.py, sirepo/tornado.py, sirepo/util.py, tests/job_timeout_test.py
For ease of mind I think we should just use one 'l' in canceled regardless of whether the value may or may not be presented to the user.
=> Fix part of #2684. Use on 'l' in canceled.

sirepo/template/madx.py
The main problem here was an incorrect equation for the ellipse, which led to the extreme bunching of points I mentioned in an earlier comment.  This takes care of that, but does not directly redistribute points.  If some combination of parameters causes a recurrence I can revisit (it involves approximating the inverse incomplete elliptic integral of the second kind, DUH).
One thing to note is that the range in x/y is about 1/10 of the range when particles are generated.  The x'/y' range matches though. I'm not sure what causes that discrepancy.
=> Fix #2723 - bad math contributed to wonky ellipses

etc/jshint.conf, etc/karma-conf.js, package.json, sirepo/package_data/static/js/sirepo.js, test.sh
Phantomjs doesn't support ES6 and it is deprecated.
Use Chrome Headless for testing instead.
This depends on radiasoft/download#115.
=> Fix #2740. Use chrome instead of phantomjs for testing.

sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/schema-common.json, sirepo/server.py, sirepo/srunit.py, sirepo/uri.py, sirepo/uri_router.py
@robnagler one possible issue: the URLS are formatted like v.radia.run:8000/*elegant in the address bar. Is this what you want or should the * be removed?
=> Fix #2652. Top-level marketing urls.

sirepo/package_data/static/js/radia.js
I had removed the condition on ```$scope.values``` to keep illegal values from even showing up in the text box.  In the interest of expediency I have put it back
=> Fix #2791 - missing condition on values in parser

sirepo/job_driver/__init__.py
Agents may still be alive even if we never received an alive message
from them. We should make an attempt to kill them to eliminate
"zombie" agents consuming resources even though the supervisor
is unaware of them.
=> Fix #2778. Kill agents in agent_starting_timeout_handler.

sirepo/pkcli/job_agent.py
The file is now in a public namespace (/tmp) so we need to cleanup
after ourselves.
=> Fix #2779. Remove fastcgi sock file in terminate.

sirepo/pkcli/roles.py
add_roles = add doesn't work because argh uses function.\_\_name\_\_ for the command name.
=> fix #2751. Deprecate *_roles names in pkcli.roles

sirepo/package_data/static/js/sirepo.js
@robnagler in https://github.com/radiasoft/sirepo/commit/d8ea1bab46d53e05ed40c59d87e3acd76912f310#r41568979 we talked about changing the regex to strip '*' (and '?') from urls. That regex doesn't work. The url coming for login before any manipulation looks like /*elegant. So I propose this.
=> Fix #2827. Strip * from url without optional params

sirepo/template/jspec.py
Apparently division was too complicated for me:/
=> Fix #2805. Use opposite of decrease/increase for fixing time step.

sirepo/package_data/static/js/ml.js, sirepo/package_data/static/js/sirepo-components.js
We just went through cleaning up this bit of code and [removing the ability](https://github.com/radiasoft/sirepo/commit/370e8da108b0e0350d1c86f0a4e3ead154ce72e2) for controllers to define the text. I added in back in some control. I'm not sure what the right way to handle this case is. The regression tab needs a different completionState string (`: {frameCount} epochs`) than the classification tab (no epochs) in the ml app.
=> Fix #2911. Do not show epoch count

sirepo/package_data/static/js/ml.js, sirepo/template/ml.py
The x dimension on the heatmap corresponds to the i (row) in the
confusion_matrix output. The y corresponds to the j (column).
=> Fix #2912. Correct confusion_matrix heatmap labels

setup.py, sirepo/package_data/static/html/elegant-visualization.html, sirepo/package_data/static/html/warpvnd-visualization.html, sirepo/package_data/static/js/elegant.js, sirepo/package_data/static/js/irad.js, sirepo/package_data/static/js/radia.js, sirepo/package_data/static/js/rs4pi.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/js/warppba.js, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/json/irad-schema.json, sirepo/package_data/static/json/ml-schema.json, sirepo/package_data/static/json/radia-schema.json, sirepo/package_data/static/json/rs4pi-schema.json, sirepo/package_data/static/json/schema-common.json, sirepo/package_data/static/json/warppba-schema.json, sirepo/srschema.py
Simulation was removed from ML app. In addition, a refactor to
move more strings onto the schema and to create consistency in messaging.
For example, in the "Welcome text" when the link to add a new simulation
says "New Dataset" then the welcome text will also say "New Dataset".
Previosly it would have said "New Simulation".
=> Fix #2934. Remove "simulation" from ML app.

sirepo/feature_config.py, sirepo/package_data/static/js/radia.js, sirepo/package_data/template/radia/examples/dipole.json, sirepo/package_data/template/radia/examples/undulator.json, sirepo/sim_data/rs4pi.py
The design tab cannot be used with the current examples, which are built from hard-coded python.  This update hides the tab.  It also fixes some other issues:
- #2995 - the json for this example was using individual fields for point coords, which is no longer correct. It's been updated to use a single comma-delimited field
- #2996 - added a line along the y axis
- #2997 - now the copy button actually makes a copy of the path
=> Fix #2927 radia example design tab error

etc/run-jupyterhub.sh, sirepo/auth/__init__.py, sirepo/auth/basic.py, sirepo/auth/bluesky.py, sirepo/auth/email.py, sirepo/auth/github.py, sirepo/auth/guest.py, sirepo/cookie.py, sirepo/events.py, sirepo/feature_config.py, sirepo/http_reply.py, sirepo/jupyterhub.py, sirepo/package_data/jupyterhub_conf.py.jinja, sirepo/package_data/nginx_proxy.conf.jinja, sirepo/package_data/static/html/jupyterhublogin.html, sirepo/package_data/static/js/jupyterhublogin.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/jupyterhublogin-schema.json, sirepo/package_data/static/json/schema-common.json, sirepo/pkcli/service.py, sirepo/server.py, sirepo/sim_api/jupyterhublogin.py, sirepo/sim_data/jupyterhublogin.py, sirepo/srunit.py, sirepo/uri_router.py, tests/conftest.py
Fix #2979.
Add support in Sirepo for running jupyterhub at sirepo.com/jupyter
To test:
`sirepo service jupyterhub`
To test with migration of data using GitHub handle:
In `sirepo.pkcli.service.jupyterhub` comment out the line setting `env=`
`SIREPO_AUTH_METHODS='github:email' SIREPO_SIM_API_JUPYTERHUBLOGIN_RS_JUPYTER_MIGRATE='1' SIREPO_AUTH_GITHUB_METHOD_VISIBLE='' SIREPO_AUTH_GITHUB_KEY='<dev_key>' SIREPO_AUTH_GITHUB_SECRET='<dev_secret>' sirepo service jupyterhub`
=> Support Jupyterhub under sirepo.com

sirepo/pkcli/job_agent.py
A state of CONFIGURING means that  resources have been allocated
to the job but the resources are being prepared for use which can
take some time.
More info:
https://www.nersc.gov/assets/Uploads/04-Running-Jobs.pdf (slide 44)
https://www.nersc.gov/assets/Uploads/pap161s2-file1.pdf (page 11)
=> Handle sbatch job state CONFIGURING.

sirepo/exporter.py, sirepo/package_data/static/js/radia.js, sirepo/package_data/static/json/radia-schema.json, sirepo/package_data/template/radia/geom.py.jinja, sirepo/server.py, sirepo/template/radia.py
Adds the ability to import binary Radia dump files. Notes:
- simulations created this way cannot be "designed" so that tab is unavailable (similar to examples)
- also added is the ability to export to a dump file. This is done by letting the template do the export if the method is defined, but maybe an ```Exporter``` class is more appropriate
=> Fix #3003 Radia dump file import

sirepo/template/radia.py
Needed to ensure the attribute exists in the dict before referencing
=> Fix #3064 - check for dmpImportFile attr first

sirepo/package_data/static/js/radia.js
Notes:
- Missing items was due to copied objects having the same ```groupId``` as the original, so the code thought the copy was already in a group and omitted it
- Removed the possibility of adding a parent group to one of its children
- Ensure deleted objects are removed from groups
=> Fix #3091 incorrect item lists

sirepo/package_data/static/html/controls-controls.html, sirepo/package_data/static/js/controls.js
In addition, make it so when the "Save Changes" button appears other
editors don't shift into rows below causing awkward spacing.
=> Fix #3086. Make the layout of editors 4 across.

sirepo/template/lattice.py
This fixes #3099
Looks like the issue is that `BeamInputFile` is used as the description for sdds_beam.input in the elegant schema instead of just `InputFile`. I wasn't sure of the significance of `BeamInputFile` so I just added it into `InputFileIterator` as a fix.
=> Issue/3099 Check for sdds_beam input during write

sirepo/sim_api/jupyterhublogin.py
In the case of the src and dst db root being the same we need to add another
check of the directories to make sure a new username doesn't conflict.
=> Fix #3159. src and dst jupyterhub db root may be the same.

sirepo/package_data/static/css/warpvnd.css, sirepo/package_data/static/html/conductor-grid.html, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/json/warpvnd-schema.json, sirepo/package_data/template/warpvnd/base.py.jinja, sirepo/package_data/template/warpvnd/optimizer.py.jinja, sirepo/sim_data/warpvnd.py, sirepo/template/warpvnd.py
I believe this covers everything outlined in #3129. @moellep and @ncook882 I don't know how to verify that these changes are working right. The simulation runs with them but I don't know if it is correct. Lmk if there is something I can do (ex demo, send python sources) to help verify the changes are correct.
@ncook882 this is the new "Emitter and Reflector Properties
" panel:
When the user double clicks on the cathode or anode on the Conductor Grid they will now be able to adjust the properties of the conductor. Ex for the cathode:
=> Fix #3129. Enable particle reflection from emitter and collector plates.

sirepo/template/code_variable.py, sirepo/template/elegant_lattice_importer.py, tests/lib_data/elegant_1/first.ele, tests/lib_data/elegant_1/first.ele.out, tests/lib_data/elegant_1/out.json
RPN namelist fields in elegant can also be strings containing shell commands
that will be evaluated by elegant. In this case just pass the string through
and do not try to evaluate it.
In the sirepo.lib case this is fine and will always work. In the Sirepo GUI
case it may not always work.
There are many possible failure points for these types of commands. For example,
when converting from elegant to madx some RPN fields we must evaluate. If the
field contains shell commands then we will get the string of the commands and
may try to do math operations on it. We will fail at that point. Another example,
is that we mangle filenames but don't mangle them in the shell commands. So, if
a user has shell commands with filenames in them the filenames will not be found
when elegant evaluates the …
=> Fix #3145. Do not evaluate RPN's that are shell commands.

sirepo/package_data/static/js/sirepo-components.js
This seems like the simplest thing we could do. It just hides the yellow "cancelled after secs" dialog once the user attempts to login. 
A more involved solution that would fix other issues would be to take some time and rework the code so we don't have to ever press the start new sim button twice (once to login, once to actually start the sim).
=> Fix #3014. Hide cancelled after secs alert when logging into sbatch

etc/run-jupyterhub.sh, sirepo/auth/__init__.py, sirepo/auth_db.py, sirepo/feature_config.py, sirepo/jupyterhub.py, sirepo/pkcli/admin.py, sirepo/pkcli/setup_dev.py, sirepo/sim_data/__init__.py, sirepo/sim_data/flash.py
jupyterhublogin is now a "proprietary" code. All new users get the
role for it. This will allow us to revoke the role later which will
prevent the user from logging in.
=> Fix #1351. Add role for jupyterhublogin.

sirepo/package_data/static/html/jupyter-name-conflict.html, sirepo/package_data/static/js/jupyterhublogin.js, sirepo/package_data/static/json/jupyterhublogin-schema.json, sirepo/sim_api/jupyterhublogin.py
I've spent a fair bit of time thinking through this but I have trouble reasoning about this code so please take a close look.
We now format github handles (make lowercase and make all non-word
characters -). This means we now must rename directories (github
handles that are different after formatting).
This solves two bugs:
1. GitHub handles may have uppercase letters in them. This was causing
a bug where users were registering with github handles with
capitalized letters and a system downstream was making the names
lowercase.
2. Underscores were possibly being encoded/decoded wrong in
usernames. We had two directories (foo_8f2 and foo_5F8f2). This made
it look like we sometimes had an randomness of 5 characters added. We
believe that 5F (hex for ascii _) was a possible encoding/decoding …
=> Fix 3267. Case issue with jupyterhub migration.

sirepo/package_data/static/html/flash-visualization.html, sirepo/package_data/static/js/flash.js, sirepo/package_data/static/json/flash-schema.json, sirepo/package_data/template/flash/examples/caplaser3d.json, sirepo/package_data/template/flash/examples/caplaserbella.json, sirepo/package_data/template/flash/examples/rtflame.json, sirepo/pkcli/flash.py, sirepo/sim_data/flash.py, sirepo/template/flash.py
This provides the "commonly used setup arguments" from
http://flash.uchicago.edu/site/flashcode/user_support/flash4_ug_4p62/node31.html
It also provides a few less commonly used arguments that are required for
CapLaserBELLA and CapLaser3D.
This branch is based on radiasoft/sirepoflash/issue/16 . Please review and merge #3266 before reviewing this.
=> radiasoft/sirepoflash#16: Allow user to configure setup command args

sirepo/auth_db.py, sirepo/package_data/static/html/flash-visualization.html, sirepo/package_data/static/js/flash.js, sirepo/package_data/static/json/flash-schema.json, sirepo/package_data/template/flash/examples/caplaser3d.json, sirepo/package_data/template/flash/examples/caplaserbella.json, sirepo/package_data/template/flash/examples/rtflame.json, sirepo/pkcli/admin.py, sirepo/pkcli/flash.py, sirepo/pkcli/setup_dev.py, sirepo/server.py, sirepo/sim_data/__init__.py, sirepo/sim_data/flash.py, sirepo/template/flash.py
~~This branch is __not__ ready to be merged. There is work to be done in the installer and possibly rsconf to handle the changes in how the distribution of FLASH is performed. But, these changes can be reviewed while I’m working on them.~~
The pr's are open: radiasoft/download#149 and radiasoft/rsconf#138
This branch is base off radiasoft/sirepoflash/issue/16-setup-command. Please review and merge #3325 before reviewing this.
Users can now upload a ZIP archive containing FLASH problem files
(F90, Config, and Makefile). These will be unpacked in the proper location
in the FLASH source code and used when compiling.
Some notable changes:
- The FLASH source code is no longer distributed as an rpm. It is
distributed as a tarball that lives in the user's lib dir.
- CapLaser3D and CapLaserBELLA …
=> radiasoft/sirepoflash#16: allow user to upload FLASH problem files

sirepo/auth/__init__.py, sirepo/auth_db.py, sirepo/auth_role.py, sirepo/cookie.py, sirepo/db_upgrade.py, sirepo/http_reply.py, sirepo/http_request.py, sirepo/job_api.py, sirepo/job_driver/__init__.py, sirepo/job_supervisor.py, sirepo/jupyterhub.py, sirepo/pkcli/admin.py, sirepo/pkcli/roles.py, sirepo/pkcli/service.py, sirepo/server.py, sirepo/sim_api/jupyterhublogin.py, sirepo/simulation_db.py, sirepo/srcontext.py, sirepo/uri.py, sirepo/uri_router.py, sirepo/util.py, tests/adm_and_own_jobs_test.py, tests/auth1_test.py, tests/conftest.py, tests/cookie2_test.py, tests/pkcli/roles_test.py, tests/proprietary_sim_types_test.py, tests/supervisor_purge_free_sims_test.py
Inside of a flask request should be the only time we touch
flask.g.  We need to use flask.g here because flask is threaded
and flask.g handles getting the right object for the thread for
us. Outside of flask (tornado, jupyterhub) we can use a global
variable because it is single-threaded. All calls must be wrapped
in a `with` to ensure we maintain the thread of control (no
`await`'s).
Fix #3348
=> Fix #3350: wrap calls to flask.g

sirepo/numpy.py, sirepo/package_data/template/ml/scale.py.jinja, sirepo/template/ml.py
I added parsing in get_application_data as well as scale.py.jinja. Also, now the comments arg in numpy.genfromtxt is set to None which means the default (`#`) won't be parsed as a comment. This seems to probably be the right default for us when parsing csv's.
=> Fix #3123. Read csv with quoted values

sirepo/job_driver/__init__.py, sirepo/job_driver/sbatch.py, sirepo/pkcli/job_agent.py
Make the number of concurrent OP_RUN per user configurable.
Also, make it so jobs in squeue (pending) can be cancelled (fix #3371).
~~This PR lead to a change in behavior. computeJobStart will now be the time the job is submitted to the queue (roughly) not the time the job actually starts. To make it the time the job actually starts running would involve more of a refactor and I think is worth a discussion.~~ With https://github.com/radiasoft/sirepo/pull/3372/commits/3f3de31188f07f2daf8e5ac68d3dd746d2d8967a this is no longer true.
=> Fix #3307: running multiple jobs at NERSC

sirepo/package_data/static/html/warpvnd-source.html, sirepo/package_data/template/warpvnd/base.py.jinja
Also fixes a bug where the generated python was invalid if an additional conductor followed an stl in the list
=> Fix #3390 - allows adding boxes to existing stl

sirepo/package_data/static/js/radia.js, sirepo/package_data/template/radia/examples/dipole.json, sirepo/package_data/template/radia/examples/wiggler.json, sirepo/package_data/template/radia/geometry.py.jinja, sirepo/template/radia.py, sirepo/template/radia_examples.py, sirepo/template/radia_tk.py
Other items fixed:
- Code meant to create sirepo model objects from python-generated examples was outdated and causing problems
- Colors of objects would get mixed between "local" and Radia-defined colors
- Copies of examples would show the (useless) 2d design tab
=> Fix #3484 radia bad boolean and others

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js
- controllers and directives on simulation detail pages no longer need to check
appState.isLoaded() or appState.whenModelsLoaded()
- any server callbacks (such as requestSender.getApplicationData()) still need the
checks in case the models unloaded before the request completed
=> fix #1608 simulation detail pages wait for appState.isLoaded()

sirepo/auth/__init__.py, sirepo/auth/email.py, sirepo/auth_db.py, sirepo/db_upgrade.py, sirepo/events.py, sirepo/job_driver/__init__.py, sirepo/job_supervisor.py, sirepo/jupyterhub.py, sirepo/pkcli/admin.py, sirepo/pkcli/jupyterhublogin.py, sirepo/pkcli/roles.py, sirepo/srcontext.py, sirepo/srunit.py, sirepo/util.py, tests/adm_and_own_jobs_test.py, tests/conftest.py, tests/cookie2_test.py, tests/supervisor_purge_free_sims_test.py
In #3505 the sqlalchemy session was not rolled back after a failed
commit. We were using a global session across the app which brought
Sirepo down.
This puts the sqlalchemy session on srcontext. The seesion is
instantiated and destroyed/rolled back with each request (in
uri_router._dispatch).
Not using a global session means that all code that needs to use the
auth_db needs to have an instantiated session. In Flask it is created
and destroyed with each request (_dispatch). For pkcli, tests, and in
the supervisor we must create the context by hand everywhere we need
it.
For pkcli we considered creating the context in
sirepo_console.py. This works fine in Flask where `sirepo service
http` ends up creating a new process so the context in
sirepo_console.py doesn't conflict with the one …
=> Fix #3505: Put sqlalchemy session on srcontext

sirepo/package_data/static/html/jupyterhub-migrate.html, sirepo/package_data/static/js/sirepo-components.js
Any markup wrapped in disableAfterClick will be disabled after they
are clicked. One can broadcast 'sr-clearDisableAfterClick' to clear
the disable.
=> Fix #3500: disable button after click

sirepo/package_data/static/js/radia.js
Two ```saveChanges()``` were overlapping, causing a race condition
=> Fix #3537 - saveQuietly lineouts on path change

sirepo/sim_data/radia.py
The root problem was 'enableKickMaps' being set to ```false``` instead of "0". Just to be safe, this catches all 'Boolean' fields and converts them to strings when needed.  Also adds 'exampleName' which handles another error obfuscated by the first (```geometry.py.jinja``` not going down the 'isExample' branch)
=> Fix #3518 - amended fixup

sirepo/template/controls.py
In 53924b0a1701c209d08006ce7d782e38c52ff4a4 _add_monitor was refactored.
b was the visualizationBeamlineId which we need to append the added
monitor to.
=> Fix #3578: b is not defined

sirepo/package_data/static/html/controls-controls.html, sirepo/package_data/static/js/controls.js, sirepo/package_data/static/js/sirepo-lattice.js
In testing it seemed that calling `getBoundingClientRect()` on the label
div multiple times yielded different results so I could eliminate
keeping track of `yOffset`.
=> Fix #3593: Prevent labels from overlapping with beamline elements

sirepo/package_data/static/json/radia-schema.json
Tested against the example that precipitated this issue. Also tested undulators with gap 0 to check that they can be solved.
Oddly, the example was a copy of the dipole example, which does not use and cannot set the gap size.  It may have come from a fairly old build?
=> Fix #3649 - accept gap size of 0

sirepo/package_data/static/js/sirepo-components.js, sirepo/template/controls.py
Notes:
- Rather than allow the user to select a kicker-less lattice (or indeed a latttice-less sim) and then get an error, I added an "invalid" property to the items in the sim list and disabled them in the dropdown
-  The name in the dropdown includes the reason why it is invalid.  I like this better than a tooltip because the feedback is immediate
=> Fix #3576 - disable invalid madx lattices

sirepo/package_data/template/radia/examples/undulator.json, sirepo/package_data/template/radia/examples/wiggler.json, sirepo/sim_data/radia.py
Notes:
- adds a field evaluation path along the y axis to the wiggler example to avoid an empty field view.  Fixes up existing sims if the user has not added a path yet
- extends the y axis path for the undulator example and adds points.  Does NOT fix up existing sims to avoid clobbering user changes
=> Example improvements

sirepo/template/template_common.py, tests/template_common_test.py
- catches the new TypeError raised when accessing groups with [()]
- adds ```pkcompat.from_bytes()``` around single-values entries 
- adds a test to ```template_common_test``` to write a dict to h5, read the file into a new dict, and compare the two
=> Fix #3704 h5py type error

sirepo/package_data/static/js/radia.js, sirepo/template/radia.py
Notes:
- The doGenerate flag was being turned off when the viewer updated
- It was not being turned off after a solve, causing the data to be reset
- Will review again when #3712 is complete
=> Fix #3741 radia data not regenerated

sirepo/template/radia.py
The "fix" to "pythonify" the offending line broke the dipole and wiggler examples, whose objects are artificially crafted and have no meaningful type. Since they will be replaced by parameterized versions shortly, this reversion will serve.
=> Fix #3913 - example objs have empty types on purpose

sirepo/auth_db.py
https://github.com/radiasoft/sirepo/blob/ce452bff87ce8f3e44894c96bcb5d8ea4d95ca6b/sirepo/simulation_db.py#L780
`verify_app_directory` ensures that the app dir exists but not that
the lib dir exists. Maybe we were in a state where the app dir existed
but not the lib dir.  This should alert us if we encounter this again.
=> WIP radiasoft/ops#645: ENOENT when trying to rename flash.tar.gz

sirepo/pkcli/srw.py, sirepo/sim_data/srw.py, sirepo/template/template_common.py
We need to check for the full path for cases when we use package_path
and multiple packages may have sirepo.sim_data._TEMPLATE_RESOURCE_DIR.
We now will search all packages until a match is found.
=> Fix #3941: Check for full file path

sirepo/feature_config.py, sirepo/job.py, sirepo/job_api.py, sirepo/job_driver/docker.py, sirepo/job_supervisor.py, sirepo/package_data/static/html/raydata-analysis.html, sirepo/package_data/static/js/raydata.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/json/raydata-schema.json, sirepo/package_data/static/json/schema-common.json, sirepo/package_data/template/raydata/parameters.py.jinja, sirepo/pkcli/job_cmd.py, sirepo/pkcli/job_supervisor.py, sirepo/pkcli/raydata.py, sirepo/sim_data/raydata.py, sirepo/template/raydata.py, sirepo/template/template_common.py, sirepo/uri_router.py
Add the 'analysisStatusPanel' to Raydata which shows the status of
selected analysis jobs and allows one to start analysis for missing
jobs. In addition, each row in the table can be clicked if the job is
running or completed. A modal will appear with the png's output from
the notebook.
Two new API's:
- runMulti: Run multiple requests in one API call. In addition, these
requests can be "fire and forget". Normall runSimulation blocks until
the simulation starts. This can take a long while if there is resource
contention. This allows starting the job, not waiting for the
response, and then polling runStatus for updates.
- analysisJob: Call template code on the agent with access to the run
dir.
=> Fix #3909: Raydata run multiple analyses

sirepo/package_data/template/srw/README.txt.jinja, sirepo/package_data/template/srw/rsoptExport.sh.jinja, sirepo/template/srw.py
Tabulated undulators are only "activated" when a ```plot_reports``` param is true. We don't want to produce plots as part of the rsopt runs (at least by default) so this adds a check for rsopt runs in the appropriate places.
Also cleans up the readme and shell script
=> Fix #3981 blicon ml tabulated und fails

sirepo/template/radia.py
This probably used to rely on ```run_dir``` and had to be amended
=> Fix #3998 - needed to set path

sirepo/simulation_db.py
I mistakenly supposed that _super was only being used by models. Also, we want views to extend their arrays (so all the subviews get copied) but do not want models to do so (because the field definitions get messed up). Another data point, I think, in favor of shifting to "real" classes and subclasses...anyway, please test against SRW etc.  Radia seems OK
=> Fix #4007 view _super broken

etc/run-supervisor.sh, sirepo/job_driver/sbatch.py
Fix #3658: log job_agent.log before overwriting when starting a new agent
In addition in dev write all log messages read from the job_agent to
the job_supervisor log stream.
Fix #2136: reset slurm node state at every start
The node on dev machines seemes to go down randomly. It is quick to
reset it so do so every time the supervisor is started in an sbatch
configuration.
=> Sbatch agent logging

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/radia-schema.json, sirepo/sim_data/__init__.py
Notes:
- I left the "UUID" field handling in place in ```SimDataBase.model_defaults```  since it could be useful, but am not opposed to ditching it
- ctrl-click of objects was not working in the radia viewer - fixed since this is a primary use of the id mapping
=> Fix #4030 radia replace uuids

etc/run-supervisor.sh, sirepo/pkcli/flash.py, sirepo/pkcli/job_agent.py, sirepo/pkcli/radia.py, sirepo/pkcli/srw.py, sirepo/pkcli/warppba.py, sirepo/srschema.py, sirepo/template/radia.py, sirepo/template/warppba.py
At NERSC we start the job_agent by supplying the sirepo command
through env (sirepo.job_driver.sbatch.sirepo_cmd). This means that
sirepo commands called from the job agent do not have the proper env.
This was causing the sim_type pkcli lookup to fail.
Modify so the assert for no `run_background` happens at server init.
This has the side effect that all sim_type pkcli's that support sbatch
must be able to be imported without being fully initialized in the
server. This is because we must assert for no run background in the
sim type initialization code (srschema.validate).
I also updated the NERSC development wiki with details on how to setup one's NERSC env to support development https://github.com/radiasoft/sirepo/wiki/Development/_compare/4b3dee65ad2f732a64ce77bbecbbda3de87fba00...29c2bcf …
=> Fix #4061: sirepo command not found at NERSC

sirepo/pkcli/radia.py
Now reflects current ```py_path```
=> Fix #4077 - pkio.py_path.local to pkio.py_path

tests/animation_test.py, tests/report_test.py
This adds tests for codes where it makes sense to do so. They are the simplest tests possible, requiring code completion (in most cases) but nothing more.
=> Sirepo 4079 run tests all codes

sirepo/package_data/static/json/srw-schema.json
```SIM_DATA.model_defaults``` should have set the default value for ```randomSeed``` ,  but the default value was null, translating to None, and was therefore skipped. Using an empty string allows the value to be set.
=> Fix #4081 - randomSeed default from null to empty

sirepo/package_data/template/srw/parameters.py.jinja
One note on this: ```pandas``` cannot read the hdf5 file because it turns out to be very limited in what it can decode. I don't think it is worthwhile to accommodate that but am flexible
=> Fix #4058 - eschew sirepo

setup.py, sirepo/smtp.py, tests/smtp1_test.py, tests/smtp2_test.py
Setting SIREPO_STMP_SEND_DIRECTLY allows smtp
to try to send directly to the server in question.
It doesn't retry so it's suboptimal, but useful
for sites that don't have a submission server
=> Fix #4015 added SIREPO_SMTP_SEND_DIRECTLY

sirepo/template/radia.py
Notes:
- moved the extruded shape handling from ```_update_geom_objects``` to ```_update_geom_obj```
- accordingly, ```update_ell``` and its cousins now just invoke ```_update_geom_obj```. They support undulator code currently under revision, and will be removed
- the extrusion length was wrong by a factor of 2 and the object mis-centered
=> Fix #4080 - fixed extrusion bug

sirepo/srunit.py, tests/animation_test.py, tests/report_test.py
This makes the animation test about a minute faster, but it still takes 2 minutes to run - about 8 seconds per server call. All sims are now expected to complete successfully. Almost all time is spent in non simulation runtime. I also removed some report tests which seemed redundant.
=> Issue/4129 Speed up animation and report tests

package.json
So the full path to the binary nor npx are needed.
Not exactly sure what was wrong with npx but it seemed to not work
when ~/src was shared over NFS between the host and vm
=> By being in the package.json the binaries are found

sirepo/pkcli/job_supervisor.py, sirepo/pkcli/service.py, sirepo/util.py
**This PR depends on radiasoft/pykern#124. Merge that before this**
Tornado's debug mode causes the server to reload whenever an imported
module changes. But, modules that aren't imported in the supervisor
(ex templates) should cause the system to reload so we pick up the
changes. When the supervisor reloads agent's are dropped and killed on
restart which forces a reload for them and any downstream processes
(ex job_cmd's).
Flask's reloader works like Tornado (reloads when imported python
module changes). But, for extra files it is only relevant to reload
flask when json files changes (ex a code's schema.json).
@mkeilman I'd like it if you gave this a try. It adds watching a lot of files. If NFS sharing between your host and vm is the culprit behind the slowdown starting the server this …
=> Fix #2431: reload supervisor and flask on file changes

sirepo/hundli_console.py
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
=> Fix #4195: yaml now requires a Loader

sirepo/job_driver/local.py, sirepo/job_driver/sbatch.py, sirepo/job_supervisor.py, tests/job_concurrency1_test.py
Previously, runSimulation requests were held open until we got resources
to run the request (prepare_send).
=> Fix #2435: reply to runSimulation request immediately (no await)

sirepo/package_data/static/js/sirepo-beamline.js, sirepo/package_data/static/js/srw.js
Lattice gets autosaved by event dispatch. Saving beamline requires considerable preprocessing that takes place in saveBeamlineChanges() in the 'beamlineBuilder' directive in sirepo-beamline.js so dispatching an event to that directive seemed like a clean way to do things.
Does the autosave need to be added to the 'start new simulation' button in the source tab as well @moellep ?
=> 4166 auto save beamline

tests/job_concurrency1_test.py
waiting on resources). This means more runStatus requests must be sent
to wait for the job to start running. So, bump the number of requests
before fail.
=> Fix #4218: increase timeout waiting for job to start running

sirepo/pkcli/madx.py
Codevar now evals the fields that UI was letting user enter as expression but was not being evaluated on the backend
=> Fix #4254 eval rpns prior to particle gen

sirepo/sim_data/radia.py
Some older simulations lack a termination array in the undulator object but do have a termination group defined in the geometryReport. When creating the new array in fixup we need to fill it to match the length of the group
=> Fix #4263 - undulator fixup fails

sirepo/srunit.py, sirepo/template/srw.py
The number of iterations between saves is n(log(n)) where n is
multiElectronNumberOfIterations. This is because the primary process
waits for all worker processes to complete an iteration and counts
that as iteration.
The cause of #4245 was since the number of cores was set to 512 a save
only occurred after 262K macro electrons. That resulted in very slow
progress for the simulation which meant no report was requested from
the GUI and so the user interface looked "stuck".
=> Fix #4245: set multiElectronNumberOfIterations to 25 in slurm and 5 everywhere else

sirepo/package_data/static/js/silas.js, sirepo/package_data/static/js/sirepo-plotting-vtk.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/js/zgoubi.js
The problem seems to stem from resize handling of the "orientation marker" after the renderer goes away. Disabling the marker when we destroy the scope gets around this.
=> Fix #4306 - disable orientation marker

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/radia-schema.json
Notes:
- It was the tooltips that were interpolated, not labels
- This then interpolates all labels, not just string array
- ```SIREPO``` gets added to the context in ```utilities``` (```appState``` cannot be, else there is a circular dependency)
- ```radia-schema``` is updated to take advantage
- Also fixes #4293
=> Fix #4291 - interpolate labels

sirepo/package_data/static/json/shadow-schema.json
The shaddow app now has a link to the user manual in the '?' icon dropdown:
This look right to you @bruhwiler
=> Fix #4313: shadow user manual in ? icon

sirepo/package_data/static/css/lattice.css, sirepo/package_data/static/js/sirepo-lattice.js
* Beamline elements are now searchable on the lattice tab.
* There is also a collapse/expand all elements option
* Categories that have been expanded and collapsed now get saved so that refreshing/revisiting the sim will not forget which element categories were expanded
* The searchbar is sticky at the top of the beamline elements panel so you don't lose it when you scroll
* Found items are scrolled into view and highlighted
=> Fix #4188: collapse and search elems

sirepo/pkcli/job_agent.py
SRW uses MPI when running in parallel. On Cori we run inside of
shifter. In order for the correct MPI libs to be loaded Cori swaps MPI
libs in the running shifter image
https://docs.nersc.gov/development/shifter/how-to-use/#using-mpi-in-shifter.
This is not working properly. So, we need to manually add the
libraries ourself.
@robnagler this is enough to get things working. Obviously, less than optimal to have to manually add these libs by hand. Also, not sure if other libraries for unused parts of mpi are missing...
=> Fix #4356: get srw running in parallel on Cori

sirepo/feature_config.py, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/srw-schema.json
Now you can turn displaying the SRW instructional video links on and off as a config option (default is on)
=> Fix #4370: remove srw video links

sirepo/sim_data/radia.py
Although the geomObject model was already handled, old models can still have references to the obsolete "box" object type scattered around elsewhere. This fix cleans them all out.
=> Fix #4394 - replace box with cuboid

sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/template/srw/parameters.py.jinja, sirepo/template/srw.py
wm_nmm added to coherent modes editor with label "Number of MPI processes groups", with default and min of 2
LMK if anything else needed for this @moellep
=> Fix #3899: wm_nmm added

sirepo/package_data/template/srw/beamline_optics.py.jinja
is_save_images is now False by default. examples/"sample from image" coherent results and partially coherent results both work with this change.
=> Fix #4133: is_save_images now False

tests/role_moderation_test.py, tests/uri_router_test.py
Calling srunit.flask_client directly circumvents setting up the work dir
for the subprocesses to run in (ex job_supervisor) which causes them
to run in the default run dir (srdb.root).
=> Fix #4504: use flask client injected by pytest

sirepo/pkcli/job_agent.py
When downloadDataFile was an analysis op, it took advantage of fastcgi, but once it became io it was a normal command, running one queued job at a time. It seems reasonable to add io ops to fastcgi.  Once I did that cloudmc was peppy.
I looked for any other analysis/io handling and the only other thing I could find is that analysis jobs are always sequential. I think it's ok for io t be parallel and it seems to work with sbatch, but it's something to consider.
=> Fix #4511 - io ops to use fastcgi

sirepo/package_data/static/html/vtk-display.html
`data-attr-width` etc. doesn't actually do anything - the overlay was expanding to fit the axes div, which had the size passed in to the directive. When that div was excluded the overlay collapsed. The sizing belongs in the style attribute.
=> Fix #4503 - moved overlay sizing to style

sirepo/package_data/static/js/sirepo-plotting-vtk.js
Binding the listeners to the sim view seems to have fixed to issue.
@mkeilman while working on this I noticed a potential bug (on my branch and master). If you move the 3d element around a lot and then try to quickly click on the simulations link you may run into the js error:
```
Cannot read properties of undefined (reading '0')
```
or 
```
Cannot read properties of undefined (reading '1')
```
I think this has to do with the coords calculations for `lCoord` still being in progress 
```javascript
viewPortPoint(worldPoint) {
// this is required to do conversions for different displays/devices
const pixels = window.devicePixelRatio;
this.worldCoord.setCoordinateSystemToWorld();
this.worldCoord.setValue(worldPoint.coords());
const lCoord = this.worldCoord.getComputedLocalDisplayValue() …
```
=> Fix #4532: radia 3d axes update

sirepo/package_data/template/srw/exportRsOpt.yml.jinja, sirepo/package_data/template/srw/parameters.py.jinja
This adds a jinja macro to replace spaces with underscores in the element title. It makes no such substitutions in the model itself.
=> Fix #4578 - jinja replace spaces with underscores

.github/workflows/python-ci.yml
Depends on radiasoft/download#287. Will fail until that is merged
=> fix radiasoft/download#285: rename workflow and installer

tests/job_concurrency1_test.py, tests/job_timeout_test.py, tests/partial_animation_test.py, tests/server_test.py
Various test timeouts needed to be adjusted to run on the slower build machine.
=> Fix #4633 test timeouts

sirepo/api.py, sirepo/server.py
@garsuga please test this branch by running `npm start` in your virtual machine, and then starting sirepo this way:
```sh
SIREPO_SERVER_REACT_SERVER=http://localhost:3000/ sirepo service http
```
I did not test updates to reactapp in real time. It's not clear how that works, because it only opens one port. However, I was able to get the basic app working just fine.
=> Fix #4617 proxy react (npm server) through server.py

sirepo/template/srw.py
Now if report == multiElectronAnimation there will not be 
`v.ws = True`
and there wont be 
`v.ws_pl = 'xy'` in paramters.py
=> Fix #4652: dont include v.ws or v.ws_pl for multiElectronAnimation

sirepo/package_data/static/html/vtk-display.html, sirepo/package_data/static/json/cloudmc-schema.json, sirepo/package_data/template/cloudmc/parameters.py.jinja
- fix #4680 two material libraries are available for selection
- fpc include vtk overlay in sr-screenshot container
- also standardize CloudMC schema labels to ucfirst on first word only
=> 4680 material library

sirepo/package_data/template/radia/examples/undulator.json, sirepo/package_data/template/radia/examples/wiggler.json
Discarding changes to example will show the correct axis now. The wiggler example had the same problem. IMHO this is not worth adding fixup code, but I will do so if needed.
=> Fix #4703 radia und example axis path

sirepo/template/srw.py
The problem was that both elliptical mirrors are named "Elliptical Mirror", so only the first mirror was deflected. `_safe_beamline_item_name` takes care of this when generating `parameters.py` (generating "Elliptical_Mirror2"), but the rsopt section passed the element names without modification.
=> Fix #4760 - handle duplicate element names

sirepo/package_data/static/css/ext/bootstrap-colxl.css, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-lattice.js
- the beamlineEditor directive now has an option headerTabInfo argument for arranging tabbed
panels within the panel heading
- fixed Object.keys() order assumption in modelArray directive and reformatted html
- added missing table css for xl and xxl layouts
=> fix #4786 beamline editor with optional panel tabs

sirepo/exporter.py, sirepo/package_data/static/js/cloudmc.js, sirepo/pkcli/cloudmc.py, sirepo/template/cloudmc.py, sirepo/template/radia.py, sirepo/template/srw.py, sirepo/util.py
Add a "Statepoints" link in the DAGMC Gemoetry report panel that downloads
a zip of all statepoint files output by the simulation.
In addition, create sirepo.util.write_zip which encapsulates all of the
args commonly supplied when creating a zipfile.
=> Fix radiasoft/prop22_cloudmc#13: export statepoints

sirepo/package_data/static/json/flash-schema.json, sirepo/package_data/static/json/radia-schema.json, sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/static/json/warppba-schema.json
tasksPerNode label renamed to 'processes per node'
=> Fix #4810: rename tasksPerNode label

sirepo/package_data/template/srw/README.txt.jinja, sirepo/package_data/template/srw/exportRsOpt_post.py.jinja
As discussed, this puts the unnormalized beam intensities into "/images" and the param values into "/metadata". Instead of a separate dataset, the parameter names now live in an attribute named "parameters" on the metadata dataset. To retrieve them, e.g.:
```python
import h5py
with h5py.File("results.h5", "r") as f:
d = f["metadata"]
p = d.attrs["parameters"]
```
This also updates the README accordingly.
=> #4816 - restructured hdf5 file

sirepo/template/srw.py
.bkp will never be selected if does not exist
if does exist, and is more recent and has sufficient line count, then .bkp is selected
=> Fix #4811: dat vs bkp slurm

sirepo/template/elegant.py, sirepo/template/template_common.py
Calls to simulation_db.simulation_run_dir have been removed and now analysis jobs take a run_dir arg.
Analysis jobs now take **kwargs.
=> Fix #4850: analysis jobs now have run_dir arg

sirepo/pkcli/raydata.py, sirepo/template/raydata.py
They were moved into the raydata scan_monitor. There will be a companion PR there.
=> Fix #4932: move all databroker calls out of sirepo.

sirepo/package_data/template/raydata/examples/chx.json, sirepo/package_data/template/raydata/examples/csx.json, sirepo/package_data/template/raydata/examples/xpcs-saxs.json
They previously lived in the private raydata repo. By moving them into Sirepo then Sirepo can create the raydata examples w/o being taught about a special place to look for them (ex package_path).
=> Fix #4974: move Raydata examples into Sirepo

sirepo/modules.py, sirepo/uri_router.py, tests/pkcli/admin_test.py
This is tricky, because quest.start calls modules.import_and_init always. This probably needs to be made more efficient, but that's how it was implemented. modules will not reinitialize if they have been already initialized. job_supervisor calls import_and_init first, which initializes uri_router without apis. When quest.start calls import_and_init('sirepo.auth'), it will be a no-op.
=> Fix #5007 init_apis not called if supervisor

sirepo/server.py
We were setting PROPAGATE_EXCEPTIONS, which doesn't seem right. It is for interactive debugging. The code for ctx popping looks at exceptions and doesn't pop contexts when exceptions are present. Not convinced this fixes it, but it's an attempt. It is not reproducible on dev.
=> Fix #5007 guess: default flask.app.config.PROPAGATE_EXCEPTIONS to False

setup.py
pyIsEmail v2.0.1 should work as expected and v2.0.0 is now yanked so can't be installed without an explicit request. As such, we no longer need to lock to a lower version than the most current one.
Apologies for the bump!
=> Fix #5003 remove version lock on pyIsEmail

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/json/radia-schema.json
The default value for a fieldPath model is an id and an empty name, with no data besides, which causes problems if the app tries to use it. This removes that from the schema, and also prevents fieldLineoutReport from running if there is no path defined.
=> Fix #4973 - removed default fieldPath, do not run if no paths

sirepo/package_data/static/html/radia-source.html, sirepo/package_data/static/js/radia.js, sirepo/package_data/static/js/sirepo-geometry.js, sirepo/package_data/static/js/sirepo-plotting-vtk.js
Notes:
- We now perform a translation on the svg shape instead of changing the object's center.
- This means that the "center" of the object does not change to reflect the new position - it is the pre-rotated center. This allows the user to drag the shape without it jumping
- Also fixes #5095 by supplying the full rotation matrix instead of a single angle
=> Fix #5085 radia rotated shapes jump

sirepo/template/radia.py
When file validation for .stl files was added, it inadvertently rejected all other file types.
=> Fix #5147 csv upload broken

sirepo/package_data/static/js/raydata.js
> Just a thought - how about show "Checking for new scans..." where the "..." changes every second, . . ...
And when it finds a new one, it could change to "Fetching scan" for a second, or until the new scan is available, and then immediately change back to "Checking for new scans..."?
Had to make a change from @moellep's [comment](https://github.com/radiasoft/sirepo/pull/4977#discussion_r1014258261), the time interval for "Fetching scan" was so short that it wouldn't show at all. So for now "Checking for new scans..." is still popping up and disappearing. I'm open to more suggestions.
=> fix radiasoft/raydata#38: loading indicator for scans table

react/src/component/reusable/heatplot.tsx, react/src/data/report.ts, react/src/layout/input/enum.tsx, react/src/layout/report.tsx, react/src/utility/compute.ts
also fixes:
- reports will 'carry on' polling and showing status after refresh
- heatplots do their min/max math correctly now
- reports will seek latest frame on refresh
- theres a WIP type for the status returned by requests like run-status
- additional states can be handled by the start simulation layout like missing and error
=> fix #5234, #5255: better report state handling

etc/run-auth-basic.sh, etc/run-auth-bluesky.sh, etc/run-bluesky.sh, sirepo/api_auth.py, sirepo/auth/__init__.py, sirepo/auth/bluesky.py, sirepo/auth/email.py, sirepo/auth_role_moderation.py, sirepo/http_reply.py, sirepo/http_request.py, sirepo/importer.py, sirepo/job_api.py, sirepo/job_supervisor.py, sirepo/oauth.py, sirepo/pkcli/service.py, sirepo/request.py, sirepo/server.py, sirepo/sim_api/jupyterhublogin.py, sirepo/simulation_db.py, sirepo/template/synergia.py, sirepo/template/zgoubi.py, sirepo/uri_router.py, sirepo/util.py, tests/auth/bluesky1_test.py, tests/auth/bluesky2_test.py, tests/server1_test.py, tests/util_test.py
- All exceptions raised are subclass of sirepo.util.Reply 
- Removed all references to werkzeug except in sirepo.pkcli.service.flask. 
- Rewrote util.secure_filename with a restricted implementation
- Replaced util.safe_path with util.validate_path with a much restricted interface to match our use
- Added run-auth-bluesky.sh and run-auth-basic.sh
=> Fix #4882 Remove werkzeug exceptions

sirepo/package_data/static/js/activait.js, sirepo/template/activait.py
If uris is undefined wont try to access items within it and will display that data file is missing in the image viewer on source. (Already displays missing data file message in sim status panel if you try to run sim)
=> Fix #5305: better datafile error for missing .h5 data file

sirepo/package_data/template/activait/train.py.jinja
Now wont reference undefined `o`
=> Fix #5482: fix csv error on nuline happiness example

sirepo/package_data/static/js/sirepo-plotting-vtk.js
When the shift key is down, the shape moves only along the axis with the largest displacement.  Works for free movement and when snapped to grid.
=> Fix #5311 radia shift move shapes single axis

sirepo/const.py, sirepo/job_driver/__init__.py, sirepo/job_driver/docker.py, sirepo/job_driver/sbatch.py, sirepo/job_supervisor.py, sirepo/pkcli/test_http.py, sirepo/tornado.py, sirepo/util.py
Change the code to:
- Catch CancelledError explicitly when needed in cases where we were relying on it to be a subclass of Exception previously.
- Remove any code that does nothing but raise on CancelledError. This pattern was used to not smother CancelledError in cases where we had an `except Exception`. Those will no longer smother the error.
In addition, in sirepo.job_supervisro.run re-raise the CancelledError and remove check for return of False from _send_op. This has no actual behavior change. We don't await _run so it doesn't matter if the CancelledError makes it out. But, it is more "correct" to not smother CancelledError and have it propagate all the way out so a cancel happens fully.
=> Fix #2447: CancelledError inherits from BaseException on > py 3.8

sirepo/nersc.py, tests/nersc_test.py
Trying this again. We need to parse the "stdout" attribute of the subprocess, not the subprocess itself. I've tested this on NERSC itself so it should behave
=> Fix #5491 nersc account error

sirepo/package_data/static/js/srw.js
now the open as shadow options is available on source, beamline and machine learning tabs
=> Fix #5515: open as shadow for all tabs

sirepo/feature_config.py, sirepo/job.py, sirepo/pkcli/job_agent.py, sirepo/pkcli/service.py
- trust_sh_env is false by default
- In non-RadiaSoft environments, will not source bashrc/profile and assume Python is correct (no pyenv)
=> Fix #5570 Add feature_config trust_sh_env for non-RadiaSoft shell environments

sirepo/feature_config.py, sirepo/package_data/static/html/rshellweg-lattice.html, sirepo/package_data/static/html/rshellweg-source.html, sirepo/package_data/static/html/rshellweg-visualization.html, sirepo/package_data/static/js/rshellweg.js, sirepo/package_data/static/json/rshellweg-schema.json, sirepo/package_data/static/json/schema-common.json, sirepo/package_data/template/rshellweg/default-data.json, sirepo/package_data/template/rshellweg/examples/drift-tube.json, sirepo/package_data/template/rshellweg/examples/emittance-conservation.json, sirepo/package_data/template/rshellweg/examples/rf-fields.json, sirepo/package_data/template/rshellweg/examples/solenoid.json, sirepo/package_data/template/rshellweg/examples/space-charge.json, sirepo/package_data/template/rshellweg/parameters.py.jinja, sirepo/pkcli/rshellweg.py, sirepo/sim_data/rshellweg.py, sirepo/template/rshellweg.py, sirepo/template/rshellweg_dump_reader.py
@moellep I think I've resurrected the backend portions of the hellweg app. 
I tested using the [attached script](https://github.com/radiasoft/sirepo/files/10887010/hellweg_test.py.txt). It runs a test for all of animations and reports in all of the hellweg examples. You can run it with the below commands:
```bash
cd ~/src/radiasoft
gcl rshellweg
cd rshellweg
CFLAGS=-I/home/vagrant/.local/include/ pip install .
cd ~/src/radiasoft/sirepo
SIREPO_FEATURE_CONFIG_SIM_TYPES='rshellweg:myapp' pykern test hellweg_test.py
```
Almost no code changes were needed. I've called out a couple places where I made some guesses on code changes but wasn't very sure.
Let me know how it looks.
=> Fix #5524: Resurrect the hellweg app

sirepo/package_data/static/js/radia.js
The camera was being reset every time the scene was built - it's only really needed after the first time.
=> Fix #5598 - set camera only after initial scene build

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/json/radia-schema.json
Notes:
- Corrects the bevels for the default parameterized c-bend dipole and moves them to the "modifications" array
- Moves the bevel for the default parameterized h-bend dipole to the "modifications" array
- Changes the label and tooltip for the "bevel edge" to clarify the geometry
=> Fix #5602 radia incorrect bevel

sirepo/feature_config.py
On systems w/o raydata as a configured sim_type this parameter shouldn't be required.
=> Fix #5612: Remove RequiredUnlessDev for raydata.file_reply_tmp_dir

sirepo/feature_config.py, sirepo/job.py, sirepo/job_api.py, sirepo/pkcli/job_cmd.py, sirepo/template/activait.py, sirepo/template/cloudmc.py, sirepo/template/controls.py, sirepo/template/elegant.py, sirepo/template/flash.py, sirepo/template/jspec.py, sirepo/template/madx.py, sirepo/template/radia.py, sirepo/template/raydata.py, sirepo/template/shadow.py, sirepo/template/silas.py, sirepo/template/srw.py, sirepo/template/synergia.py, sirepo/template/template_common.py, sirepo/template/webcon.py, sirepo/template/zgoubi.py
Pass on the dataFileUri all the way to the scan_monitor and have it put the file. This eliminates the need for shared directories or any unnecessary marshalling/unmarshalling of the file on the way back.
=> WIP radiasoft/raydata#83: Have raydata.scan_monitor send file to supervisor

sirepo/template/radia.py
Offending points have been excised from the `_get_<type>_points()` functions.
=> Fix #5700 - removed last point for each shape type

sirepo/package_data/static/js/radia.js
The new path was being copied to the fieldLineoutAnimation model before all the parameters were set. Waiting for the save to complete ensures that they are.
=> Fix #5854 - update path on save, not change

react/src/utility/compute.ts, sirepo/feature_config.py, sirepo/http_request.py, sirepo/job_api.py, sirepo/package_data/static/react-json/shadow-schema.json, sirepo/pkcli/shadow.py, sirepo/server.py, sirepo/sim_data/__init__.py, sirepo/sim_data/madx.py, sirepo/sim_data/shadow.py, sirepo/simulation_db.py, sirepo/template/code_variable.py, sirepo/template/lattice.py, sirepo/template/madx.py, sirepo/template/madx_converter.py, sirepo/template/madx_parser.py, sirepo/template/shadow.py, sirepo/template/template_common.py, tests/template/srw_shadow_data/to_shadow_crl.out/shadow.json, tests/template/srw_shadow_data/to_shadow_gauss.out/shadow.json, tests/template/srw_shadow_data/to_shadow_grating.out/shadow.json
Revert shadow server side to old data format. Un/format react data as needed.
unformat react data hooks
- simulation_db.fixup_old_data()
- job_api._request_content()
format react data hook
- server.API._simulation_data_reply()
React data un/format code takes place in sim_data subclasses using the methods 
```python
def react_format_data(cls, data)
def react_unformat_data(cls, data)
```
=> 5914 shadow conversion

sirepo/package_data/static/js/sirepo-components.js
The only permutation that seems to work is to get rid of the one-time evaluation of canShowDocumentationUrl()
=> Fix #5991 - omit one-time eval

sirepo/auth/email.py, tests/auth/email1_test.py
In 791364f18d02e28307ffb0101e4ebab488a13e02 the api_authEmailAuthorized code was changed from passing the user model we acquired based on searching by the email token to one acquired by searching for the uid into auth.login.
Previous behavior: https://github.com/radiasoft/sirepo/commit/791364f18d02e28307ffb0101e4ebab488a13e02#diff-109de77eab3047455095be7e4c1f5f1d918083adaa02b87d5c862a8e513e8436L61
Behavior introduced in 791364f18d02e28307ffb0101e4ebab488a13e02: https://github.com/radiasoft/sirepo/commit/791364f18d02e28307ffb0101e4ebab488a13e02#diff-109de77eab3047455095be7e4c1f5f1d918083adaa02b87d5c862a8e513e8436R89
But, the uid isn't present on the model. auth.login creates the user and populates the uid. In the case where we have multiple records in auth_email_user_t without a uid the …
=> Fix #6083: auth.login creates the uid

sirepo/template/radia.py
We now accept file types regardless of case
=> Fix #6121 - use lower() on file types to validate

sirepo/template/radia.py, sirepo/template/radia_util.py
We now shift the stl vertices such that the bounding box center, and not the stl's centroid, is at the user-specified center. Note `stlCentroid` is still provided for possible future use.
=> Fix #6184 radia stl position

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/js/sirepo-plotting-vtk.js
This applies symmetries to groups recursively. Bonus flipping of expansion carets in the object list to conform to convention.
=> Fix #6304 radia xform subgroup shapes

sirepo/package_data/static/js/sirepo-plotting-vtk.js
The objectEquality parameter to angular's $watch needed to be _true_ to trigger the refresh. Otherwise it just senses changes to the reference.
=> Fix #6326 - set objectEquality true in watch

sirepo/sim_data/radia.py
=> Fix #6443 - skip non-dict models

sirepo/package_data/static/js/cloudmc.js, sirepo/package_data/static/js/sirepo.js
Notes:
- `multiLevelEditor` for filters contains five instances of the type dropdown; but without modification, `showEnum()` would apply only to the first instance of `optionIndex`
- Accordingly, this has `showEnum()` apply to all the corresponding options in each instance
- `showEnum()` also now takes a parameter to address an optional index for a specific instance
=> Fix #6454 cloudmc filter types

sirepo/oauth.py, sirepo/request.py
This is a partial fix to get flash oauth working again. There are two aspects that were/are broken:
1. When setting up the tornado _SRequest http_request_uri only added the path to the protocol and host. In the case of flash this was /sim-oauth-flash-authorized. But, this missed all of the query params (?code=xxx). So, authlib would raise a
"MissingCodeException". Changing to full_url() fixes this.
2. Oauth wasn't working in dev because websockets and our oauth flow are incompatible. We do Set-Cookie when returning the oauth flow redirect but I believe the redirect response is in a websocket so Set-Cookie has no impact.
For now, point 2 isn't a problem on prod. We only use websockets in dev and alpha. So, I want to push this fix through while a figure out a fix for websockets.
=> Fix #6378: Get flash oauth working again

sirepo/template/code_variable.py, tests/template/code_variable_test.py
Notes:
- This modifies `__eval_python_stack()` rather than the higher level `eval_val()` to recurse properly
- We therefore need to convert sub-expressions to postfix
- The tests cover likely scenarios, including expected failure of expressions like "x + array[0]"
=> Fix #6503 - array value handling and tests

sirepo/template/code_variable.py, tests/template/code_variable_test.py
The main feature here is `__eval_indexed_variable ()`. It looks for substrings of the form <variable>[<index>] and replaces them with the variable's value at that index. e.g. for a variable:
```python
a = PKDict(name=a, value=[1, 2, 3])
```
an expression
```python
'1 + a[0]'
```
will become
```python
'1 + 1'
```
For expedience, this is strictly a regex substitution, not a modification of the parse tree. Anything more complicated (like say <variable 1>[<variable 2>] should probably involve the latter.
The test which used to expect a failure of these expressions now expects them to pass.
=> Fix #6516 code var array expressions

sirepo/package_data/raydata-execute-analysis.sh.jinja
After some testing we determined that the dir needs to be created in prod as well as dev. So, just create it in all cases.
=> Fix #6553: create the output dir in all cases.

sirepo/package_data/static/js/sirepo-dom.js
`SVGPath.update()` was calling `pathPoint()` instead of `pathPointAt()` - in fact `pathString()` is already dong the right thing and the bulk of the update code was redundant.
=> Fix #6597 radia button shapes

sirepo/template/radia_util.py
The issue was in `_update_extruded()`, which refers to `radia_util.AXIS_VECTORS`, where `numpy.array([1, 0, 0])` etc. creates an array of `numpy.int64`. The simple expedient of using `numpy.array([1.0, 0, 0])` gets past this.
=> 6599 radia param dipole 64 bit

sirepo/package_data/template/radia/examples/undulator.json, sirepo/sim_data/radia.py
Adds the geomGroup type to the undulator example and has a fixup for missing type fields
=> Fix #6580 - add geomGroup type and fixup

sirepo/srunit.py
tests/import_test.py was failing on our servers. So, increase the timeout.
=> Fix #6619: Increase CPU divisor

sirepo/job_driver/__init__.py, sirepo/job_driver/docker.py, sirepo/job_driver/local.py, sirepo/job_driver/sbatch.py, sirepo/job_supervisor.py, sirepo/pkcli/job_agent.py, sirepo/status.py, tests/job_timeout_test.py
- Changed some conditionals to assertions to simplify code
- Locking around start and end of the agent life (_agent_life_change_lock)
- Ops are bound to driver in prepare_send, was too early in agent_start
- Fix #6613 _agent_start_delay is local to op
- Fix #6572 added more logging, fixed some messages, and normalized others
- Cleaned up some naming (opId > op_id when not in msg)
- Cascade exceptions into op.internal_error for better logging
- Improved error handling/logging in sirepo.status
=> Fix #6608 normalized job_driver's agent life cycle code

sirepo/package_data/static/css/raydata.css, sirepo/package_data/static/js/raydata.js, sirepo/package_data/static/json/raydata-schema.json, sirepo/raydata/scan_monitor.py, sirepo/sim_data/raydata.py, sirepo/template/raydata.py
- fix #6581 and fix #6420 search for a specific field
- fix https://github.com/radiasoft/sirepo/issues/6191 column list refreshed from each scan result
=> fix #6585 scan_id is searchable, added individual field search

sirepo/package_data/template/elegant/examples/script-element.json, sirepo/package_data/template/elegant/lib/SCRIPT-commandFile.combine.py
The elegant Script Element Example now uses a new python script to merge two beams together, and doesn't add new particles.
=> fix #3915 update script example

sirepo/job.py, sirepo/job_api.py, sirepo/package_data/static/json/schema-common.json, sirepo/package_data/static/react-json/common-schema.json, sirepo/pkcli/job_supervisor.py, sirepo/uri_router.py
Uses of runMulti were removed in
7f4f427f21cb71a60a9ba7dcce54ffd94e263b81. So, remove the API since it is unused.
=> Fix #6698: remove api runMulti and related code

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js
This change shows a modal dialog for two cases, invalidSimulationSerial and newRelease.
=> fix #6366 show refresh modal when serverUpgraded detected

sirepo/package_data/static/js/raydata.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/raydata-schema.json, sirepo/raydata/analysis_driver/__init__.py, sirepo/template/raydata.py
- fix #6737
- fix radiasoft/raydata#148
- this version of papermill doesn't have a lot of options, so the easiest way to achieve this was to add back the progress bars
- fix #6741 
- fix #6736
- I was inspired by the Gmail example we looked at the other day, where the loading spinner is in the middle of the page and then "no results" is at the top. I wasn't sure if we had any official design language decisions regarding loading spinners like this one (feedback welcome @mkeilman)
=> fix #6737 raydata ui changes

sirepo/package_data/static/js/cloudmc.js
This seems to work fine on my laptop screen but I'd like to know how it fares on bigger screens...
=> Fix #6716 - use 90% instead of 90vh

sirepo/job_driver/__init__.py, sirepo/job_supervisor.py
- increase purge_free_simulations asynchrony to avoid I/O blocking
which may be an issue with a few recent failures we have seen.
- Added a bit more logging, especially start/done on purging
=> Fix #6779 improve supervisor logging and asynchrony

sirepo/job_api.py
This avoids "tornado.simple_httpclient.HTTPTimeoutError:Timeout in request queue"
=> Fix #6816 set AsyncHTTPClient to force_instance=True

sirepo/package_data/static/js/raydata.js, sirepo/raydata/scan_monitor.py, sirepo/template/raydata.py
also fix #6587 show queue order on pending list and allow sorting on queue order 
Scan items may be moved to the front or back of the list
=> fix #6588 Allow analysis queue to be reordered

sirepo/package_data/static/js/cloudmc.js
Notes:
- The NaN errors were caused by a source particle vector being aligned with the slice axis (hence no size in the plane and a divide by 0)
- This sets the endpoints of the vector to be the same in that case
- Any source particles outside the 2d plot range are now omitted
=> Fix #6837 cloudmc path nan

sirepo/package_data/static/js/cloudmc.js
Note we just watch numSteps since that is the only property used to show or hide the field
=> Fix #6892 - watch planePos.numSteps

sirepo/srunit_servers.py, tests/conftest.py
Fix #6887 each call to pytest_runtest_protocol is new,
because pykern.pkcli.test runs each test in a spearate process.
=> Fix #6809 missing terminate call

sirepo/job.py, sirepo/job_driver/__init__.py, sirepo/job_driver/sbatch.py, sirepo/pkcli/job_agent.py, sirepo/srunit.py, tests/sbatch_test.py
- In the cancel case we don't have fields like simulationType. We just have opId's to cancel. So, we can't construct userDir. But, we don't need userDir (or runDir, sbatchCores, etc) in the cancel case (or for any non SLOT_OPS). So, only add those fields when not SLOT_OP.
- Add a check inside of the job_agent for op_name to keep job_driver.sbatch and job_agent in sync. job_agent._Cmd's require fields like runDir.
- Add a test for sbatch cancel which wasn't covered previously.
=> Fix #6972: Fix cancel in sbatch

test.sh
AngularJS sometimes gives an error depending on where the quotes are. To recreate a case where it fails silently, change a data-ng-switch-when in AppFieldEditors to use smart quotes, ex:
`data-ng-switch-when="SimArray"` -> `data-ng-switch-when=“SimArray”`.
=> fix #6756: Check for smart quotes in js

sirepo/server.py, tests/uri_router_test.py
In the case where we can't correctly parse a uri (ex unknown uri
or required params missing) then we default to api_notFound but
still pass through the args from the original route. So, make
api_notFound capable of handling any args and just ignoring them.
=> Fix #7111: Make api_notFound capable of handling any args

sirepo/package_data/static/json/openmc-schema.json, sirepo/package_data/template/openmc/examples/zpre.json, sirepo/package_data/template/openmc/parameters.py.jinja
- Added additional material library choices: ENDFB-8.0-NNDC and FENDL-3.1d
- Use temperature.method "interpolation"
- Update zpre example to use the ENDFB-8.0-NNDC which has multiple temperatures
=> fix #7117 zpre simulation now runs with material temperature

sirepo/http_util.py, sirepo/pkcli/job_supervisor.py, sirepo/request.py, sirepo/uri_router.py
Some proxys set the remote ip in this header.
=> Fix #7222: Handle 'proxy-for' header

sirepo/package_data/static/html/simulations.html, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/raydata-schema.json, sirepo/package_data/static/json/schema-common.json
It doesn't make sense for the Raydata app to create new simulations.
Also, rename "notebook" to "analysis" which fits the app better.
=> Fix radiasoft/raydata#176: remove ability to create new simulations

tests/parse_error_log_test.py
in non-dev mode, predefined.json must be there, but is removed in srunit_servers so need to narrow sim types to absolutely necessary
=> Fix #7324 avoid srw predefined.json check

sirepo/package_data/static/js/sirepo-lattice.js
- the fix was to ensure the drop target element was also the scrollable element, not the parent
=> fix #7338 drop new element into a scrolled beamline editor

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/srw.js, sirepo/template/srw.py
- updated autoSave to display an alert if an error occurs during save
- protect against NaN intensity ranges on the client (for cached plot data) and on the server
=> fix #7433 ensure computed intensity limit return a valid number

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js
- request the most recent pending frame when a prior frame completes
=> fix #7116 only send one frame request at a time to the server

sirepo/package_data/static/css/vtk.css, sirepo/package_data/static/html/vtk-display.html, sirepo/package_data/static/js/openmc.js, sirepo/package_data/static/js/radia.js, sirepo/package_data/static/js/sirepo-plotting-vtk.js, sirepo/package_data/static/json/openmc-schema.json, sirepo/package_data/template/openmc/parameters.py.jinja, sirepo/sim_data/openmc.py, sirepo/template/openmc.py
fix #7183 validate mesh dimensions are positive
=> fix #7034 require tally score and mesh

sirepo/status.py, tests/conftest.py, tests/status_test.py
- Fixed conftest.py to parse fc_args always
=> Fix #7536 add SIREPO_STATUS_REPLY_SENTINEL

sirepo/auth/__init__.py, sirepo/auth_role.py, sirepo/feature_config.py, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js
Turning off SIREPO_FEATURE_CONFIG_USER_MODERATION will stop moderation requests.
=> fix #7545 no moderation required for non-email authentication methods

etc/run.sh, sirepo/const.py, sirepo/feature_config.py, sirepo/jupyterhub.py, sirepo/pkcli/admin.py, sirepo/pkcli/jupyterhublogin.py, sirepo/pkcli/service.py, sirepo/sim_api/jupyterhublogin.py, sirepo/util.py
jupyter is independent of prod/non-prod codes. We either want it enabled or not and we don't really care that it works by using a sim type. So, move the configuration into an explicit variable.
On sirepo alpha this will allow us to keep the existing configuration (not specifying sim types) while moving jupyterhublogin from a moderated_sim_types to just a sim_type (sirepo is now moderated across the board).
=> Fix #7541: Enable jupyter explicilty (not through sim type)

sirepo/package_data/static/json/cortex-schema.json, sirepo/package_data/static/json/schema-common.json, sirepo/simulation_db.py, sirepo/uri_router.py
- apps can now define extra routes to sim_apis in the app schema
- moved cortexDb route from schema-common to cortex-schema
=> fix #7666 use feature_config.package_path when looking up sim_apis
