radiasoft/sirepo

sirepo/sirepo_parser.py
Hello Rob, Paul,
Here is a fixed parser for a watch point report. I will continue to implement reformatting of the parser/importer.
Thanks,
Maksim
=> Importer fixed to process watch point reports correctly.

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/html/plot2d.html, sirepo/package_data/static/js/sirepo-plotting.js
Hi Paul,
Here I implemented improvements for 2D-plots for #84 and #107:
- format of the displayed coordinates is corrected;
- copying of the coordinates by double click on the local maxima points is implemented.
Please revise the code and let me know about any issues or concerns about the implementation and security.
Thanks,
Maksim
=> Plots improvemets for #84 and #107

tests/importer_data/lcls_simplified.json, tests/importer_data/lcls_simplified.py, tests/importer_test.py
Hi Rob,
LCLS simplified test was added to the test suite. Please revise and merge it.
Thanks,
Maksim
=> LCLS simplified test added

sirepo/importer.py, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/srw.js, sirepo/server.py
Hi Rob & Paul,
Let's review my implementation of the optional arguments together, so we can address correctness of the code and possible security issues.
Thanks,
Maksim
=> Implementation of optional input arguments for #104

README.md
After going through the readme on a fresh machine, these are some recommendations.
Minor stuff that likely doesn't come up on machines already configured for development.
=> Minor README touchups

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/schema-common.json, sirepo/server.py, sirepo/sr_unit.py, sirepo/template/elegant.py, sirepo/template/elegant_common.py, sirepo/template/elegant_lattice_importer.py, sirepo/template/fete.py, sirepo/template/shadow.py, sirepo/template/srw.py, sirepo/template/warp.py, tests/server_test.py
Paul let me know if the fix looks ok. I added a parameter to get_data_file called "suffix" rather than "type" or "format", which are problematic from a Python point of view. This allows multiple formats. I didn't add assertions to the other codes for suffix, fyi.
=> Fix #719: Added elegant.csv download

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/html/elegant-visualization.html, sirepo/package_data/static/js/elegant.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/elegant-schema.json, sirepo/template/elegant.py
parameterTable is saved on changes. Formatting matches editor panel. Formatting m$be$nc with sanitized ng-bind-html.
=> Fix #719: elegant parameter view

sirepo/package_data/static/html/elegant-visualization.html, sirepo/package_data/static/js/elegant.js, sirepo/package_data/static/js/fete.js, sirepo/package_data/static/js/hellweg.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/js/warp.js, sirepo/package_data/static/json/elegant-schema.json, sirepo/package_data/static/json/schema-common.json, sirepo/pkcli/elegant.py, sirepo/pkcli/warp.py, sirepo/template/elegant.py, sirepo/template/fete.py, sirepo/template/hellweg.py, sirepo/template/template_common.py, sirepo/template/warp.py
I ran all the apps. animationArgs is now parsed in template_common.parse_animation_args(). Interface isn't ideal, but would be better if model driven off the schema. Didn't have time for more changes.
=> Touched all animationArgs so needs review

README.md
First attempt at some simple edits to Sirepo ReadMe.md
=> Small Edits to ReadMe.md

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/json/warpvnd-schema.json, sirepo/template/template_common.py
This leverages the existing field validation with a "SafePath" type - each application schema would require an update (only warpvnd is included here). Also displays a warning message when the user enters invalid text, details of which merit further discussion
=> Fix for issue #809

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/js/elegant.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/elegant-schema.json, sirepo/template/template_common.py
I worked with the elegant format of a comma-delimited string, so there is a certain amount of dis/re-assembly.  See also the validation in template_common.py 
Labels for the lists are tacked on to the end of the array in the schema
I did not change the pop-up text but it might be worth a look considering the UI change
=> For Issue #716 - Separated distribution type into 3 drop-down lists

sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/srw.js
This hides the start/stop buttons and runs the flux simulation automatically if the approximate method is selected. The simulation remains persistent. Still requiring thought is proper handling of queue conflicts in the cancelation process
=> Added autorun for Issue #213

sirepo/package_data/template/srw/parameters.py.jinja, sirepo/template/srw.py
This PR fixed testing for existence of the mirror profile file.
Should we raise if the file is not found or just silently proceed with calculation?
=> SRW: fix missing mirror profile file

sirepo/pkcli/srw.py, sirepo/template/srw.py, sirepo/template/srwl_uti_brightness.py, sirepo/template/template_common.py, tests/importer_test.py, tests/server_test.py
=> Fix py36 support

sirepo/package_data/static/html/index.html, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-lattice.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/json/schema-common.json, sirepo/package_data/static/json/shadow-schema.json, sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/static/json/warpvnd-schema.json, sirepo/simulation_db.py, sirepo/util.py
=> Added dynamic mod for beamline (#1299)

sirepo/package_data/static/js/sirepo.js
=> Fix for re-opened Issue #907

sirepo/package_data/static/json/srw-schema.json, sirepo/template/srw.py
=> ENH: fix crystal diffraction angle to have enum values

sirepo/package_data/static/css/landing-page.css, sirepo/package_data/static/html/landing-page-elegant.html, sirepo/package_data/static/js/landing-page.js
=> Landing page fixes

sirepo/package_data/template/warppba/parameters.py.jinja, sirepo/template/warppba.py
This will break when we stop having a single fixed run_dir path.
See gh-1545.
=> Don't hard-code the run_dir path into warppba's parameters.py

sirepo/template/srw.py, sirepo/template/srw_importer.py, tests/template/srw_magmeaszip_test.py, tests/template_common_test.py
Notes:
- Looks like some zip tests are duplicated and can be removed from ```template_common_test.py```, but I'll defer that for the moment
- Not sure about ```scipy.ndimage.zoom``` - it seems like the try-except is specifically there for the zoom import...???
=> Python refactor import misc

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/html/plot2d.html, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/template/webcon.py
Notes:
- The option to plot as individual points is currently added to the plot data returned by webcon.py, but should be up to the user.  Leaving for later
- Also included is a laTeX label displaying the equation with best fit parameters filled in
=> Fix #1559 - Scatter plots

sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/webcon.js, sirepo/template/webcon.py
The basics of this are complete - further changes can go to subsequent issues
=> Webcon fit plot

sirepo/package_data/static/html/webcon-analysis.html, sirepo/package_data/static/js/webcon.js, sirepo/package_data/static/json/webcon-schema.json, sirepo/pkcli/webcon.py, sirepo/template/webcon.py
First iteration of fft, sure to be refined
Notes:
- Uses scipy's fft routines (numpy is essentially identical)
- Negative frequencies omitted
- Principal frequencies found via comparison to average and displayed with the plot
=> Webcon fft

sirepo/template/webcon.py
Added a missing factor of 2π, plus a units change
=> Webcon fft fixes

sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/json/webcon-schema.json, sirepo/template/template_common.py, sirepo/template/webcon.py
Notes:
- Now showing only x and y once in legend
- Default and minimum time window now 30s
- Default and minimum sample period now 5s
- Using svg ```<symbol>/<use>``` tags to draw plotting symbols
=> Webcon epics simplify plots

sirepo/base_pkconfig.py, sirepo/runner_daemon/docker_process.py
This is technically part of SOW-4, but it's self-contained and
ready-to-review. Up to you whether you want to treat it as its own PR
or wait for the rest of SOW-4.
=> In dev env, use local python env even when running in docker

sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/template/srw/beamline_optics.py.jinja, sirepo/package_data/template/srw/beamline_parameters.py.jinja, sirepo/template/srw.py, sirepo/template/warpvnd.py
1, add transmission Image to sample field
2, modify the name to Electron Beam with Arbitray Magnetic Field;
3, modify something about the "electron beam" and 'undulator'. still working on this.
=> add transmission Image to sample field

sirepo/package_data/static/js/sirepo-components.js
After discussion, removed link entirely for everything except elegant and srw, whose behavior is unchanged
=> Removed link from app name

sirepo/package_data/static/js/warpvnd.js, sirepo/package_data/static/json/warpvnd-schema.json, sirepo/template/warpvnd.py
Ultimately due to lack of default color.  This adds a default color for new conductors and some fixup code to handle existing conductors
=> Fete reflection

sirepo/package_data/static/json/srw-schema.json, sirepo/template/srw.py
We added the "image rotation" function for all "plot3d" reporting and we have tested it. Now we request a pull. Thanks a lot!
=> the image rotation for "plot3d" report.

sirepo/package_data/static/js/warpvnd.js, sirepo/template/warpvnd.py
Also fixes invoking ```float()``` on an empty slice string
=> Fixed bug where polygons not saved

sirepo/auth/__init__.py, sirepo/comsol_register.py, sirepo/http_reply.py, sirepo/runner/background.py
See https://github.com/radiasoft/sirepo/issues/2014#issuecomment-548151118
=> Fixing undefined errors

sirepo/exporter.py
=> Correct filename for export as zip

sirepo/pkcli/db.py
=> skip src user

etc/run-supervisor.sh, sirepo/job_api.py, sirepo/job_driver/docker.py, sirepo/job_driver/local.py, sirepo/pkcli/job_agent.py
=> move mpi config to drivers

sirepo/auth/__init__.py, sirepo/job.py, sirepo/job_api.py, sirepo/job_supervisor.py, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/schema-common.json, sirepo/simulation_db.py, test.sh
authState.jobRunModeMap is returned
job_api throws exception if jobRunMode not valid
Schema is configured in authState factory to correct display values
=> Fix #2198 JobRunMode static in schema

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/srw.js
=> default to parallel if sbatch jobRunMode is no longer available

sirepo/job.py, sirepo/job_driver/__init__.py, sirepo/job_supervisor.py, sirepo/pkcli/job_agent.py
1. Log all resource awaits in supervisor
2. Send stderr from job_cmd back to supervisor  and log it in supervisor
Fix #2254
=> More logging

sirepo/simulation_db.py
=> add rsmanifest information to in.json

sirepo/job_driver/__init__.py, sirepo/job_driver/docker.py, sirepo/job_supervisor.py, sirepo/template/myapp.py, tests/job_timeout_test.py
=> check for idle docker agents every 30 min

etc/run-auth-email.sh, setup.py, sirepo/auth/__init__.py, sirepo/auth/github.py, sirepo/auth_db.py, sirepo/feature_config.py, sirepo/github_srunit.py, sirepo/http_request.py, sirepo/job.py, sirepo/job_driver/__init__.py, sirepo/job_driver/docker.py, sirepo/job_driver/local.py, sirepo/job_driver/sbatch.py, sirepo/job_supervisor.py, sirepo/package_data/static/js/sirepo.js, sirepo/pkcli/job_agent.py, sirepo/pkcli/job_supervisor.py, sirepo/template/myapp.py, tests/conftest.py, tests/job_timeout_test.py, tests/proprietary_sim_types_test.py
=> add ws ping interval/timeout; move all ws cfg onto job.cfg

sirepo/package_data/static/json/jspec-schema.json
Fix #2317
@robnagler This requires building the latest jspec
=> fix #2317 add meshkov force forumala

sirepo/package_data/static/js/jspec.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/json/jspec-schema.json, sirepo/package_data/template/jspec/examples/booster-ring.json, sirepo/package_data/template/jspec/examples/dc-cooling.json, sirepo/sim_data/jspec.py
Fix #1158.
This just fixes the 1st bullet point from [moellep's comment](https://github.com/radiasoft/sirepo/issues/1158#issuecomment-596611744) (adding time_step field).
We've decided that the second bullet point will require some refactoring which will be done in
=> Update time, number of steps, and time step according to eachother

sirepo/job_supervisor.py, tests/animation_test.py
Also fixes the missing write reported in https://github.com/radiasoft/sirepo/issues/2379#issuecomment-601802547
=> Fix #2381 Encapsulate pkupdate/db_write in supervisor

setup.py, sirepo/auth/email.py, sirepo/auth/github.py, sirepo/auth_db.py, tests/adm_and_own_jobs_test.py
=> Remove flask-sqlalchemy so db can be used by job_supervisor

sirepo/job_supervisor.py, sirepo/pkcli/job_cmd.py
=> We are using jsonl so a message ends at a newline character.

sirepo/package_data/static/js/irad.js, sirepo/package_data/static/js/sirepo-geometry.js, sirepo/package_data/static/js/sirepo-plotting-vtk.js, sirepo/package_data/static/json/irad-schema.json
=> 3d solid from ROI points

sirepo/pkcli/service.py, sirepo/pkcli/test_http.py
This branch is based on the issue/1560 branch. Please merge that first. It also requires the cpu slot allocation fix from #2444 to ever successfully finish. #2444 is not currently in this branch once #2444 is stable I'll merge it in.
=> fix #2204 finish async tester

sirepo/job_api.py, sirepo/job_driver/__init__.py, sirepo/job_driver/docker.py, sirepo/job_driver/local.py, sirepo/job_driver/sbatch.py, sirepo/job_supervisor.py, tests/conftest.py
Also fixes:
* asyncio, resources, errors, locks, etc. #2467
* configure SIREPO_CONFTEST_MAX_CASE_RUN_SECS #2471
* conftest sometimes does not stop on max_case_run_secs #2472
=> fix #2443 job_driver cpu slot allocation does not wake all waiters 

sirepo/job_driver/__init__.py, sirepo/job_driver/docker.py, sirepo/job_driver/local.py, sirepo/job_driver/sbatch.py, sirepo/job_supervisor.py
Also, minor refactor to remove instances of "req" from
job_driver/*. Driver's only work with op's not req's.
=> Fix #2475, move assigning of a driver into _Op declaration.

etc/run-supervisor.sh, sirepo/job_driver/__init__.py, sirepo/job_driver/docker.py, sirepo/job_driver/local.py, sirepo/job_driver/sbatch.py, sirepo/srunit.py, tests/conftest.py
* Fix report_test not running zgoubi since py3 change 4c2f4a00
* Fix srunit.sr_run_sim to iterate timeout loop correctly 7ef9c71a
* Fix run-supervisor.sh ssh instructions to include nersc_user a174eb5b
=> Fix #2483 sbatch creds and agent_timeout_secs use

sirepo/pkcli/admin.py
=> Fix #2510. Check to make sure proprietry sim_type is one of the

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js
This addresses https://github.com/radiasoft/sirepo/issues/2278#issuecomment-633230568.
It makes is clear that the user must press the start button.
=> Fix #2278. Improve NERSC login.

sirepo/feature_config.py, sirepo/pkcli/admin.py, sirepo/simulation_db.py, tests/feature_config_test.py
=> Fix #2544 proprietary_sim_types added to sim_types

sirepo/package_data/static/html/flash-physics.html, sirepo/package_data/static/html/flash-source.html, sirepo/package_data/static/js/flash.js, sirepo/package_data/static/json/flash-schema.json, sirepo/package_data/template/flash/default-data.json, sirepo/package_data/template/flash/examples/caplaserbella.json, sirepo/package_data/template/flash/examples/rtflame.json, sirepo/sim_data/flash.py, sirepo/srschema.py, sirepo/template/flash.py
**Do not** merge this PR. Lmk when it is approved and I will merge it. It has changes that are going to conflict with the other open flash PRs and I want to make sure they all get sorted out properly. Ideally we would merge the other flash PRs before this one.
This PR covers more than just the changes requested in the issue.
While working on the issue I ran into numerous problems with the ":"
in the model names (ex jquery selector didn't like it,
werkzeug.secure_filename stripped them). After discussion with @robnagler 
I tried using ^ instead of : but the problems persisted. Ultimately,
it was best just to use no special characters. This make some of the
model names more challenging to read but simplifies everything else.
=> Fix radiasoft/sirepoflash#4. Discharge configuration in source tab.

sirepo/package_data/static/html/srw-beamline.html, sirepo/package_data/static/html/srw-source.html, sirepo/package_data/static/js/sirepo-beamline.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/json/srw-schema.json, sirepo/template/srw.py, tests/karma/label_test.js, tests/model_defaults_test.py
- create dynamic View directives when an UI editor is created for app business logic
- allow angular expressions in field label tooltips
- added PanelState enableFields() and showFields() to allow mass field updates
- update SRW app to use new view and beamline logic
- no longer need to create modal dialogs linked to the controller in html templates
=> Changes for #2706 refactor editor business logic

container-conf/radia-run.sh, sirepo/feature_config.py, sirepo/pkcli/service.py, sirepo/pkcli/test_http.py, sirepo/srunit.py
generate random server secret
set use_reloader to false in radia-run.sh
take out unnecessary vars
reuse code in feature_config to make more readable
=> Fix #2762 add use_reloader, hide_guest_warning in dev

etc/jshint.conf, etc/karma-conf.js, package.json, sirepo/package_data/static/js/sirepo.js, test.sh
requires chromeheadless so need latest beamsim
=> Fix #2806 install karma

sirepo/package_data/static/js/sirepo.js
generate two maps like in uri_router
formatUrl uses maps to render uri properly
=> fix #331 formatUrl parses params properly

sirepo/package_data/static/js/srw.js, sirepo/package_data/template/srw/beamline_optics.py.jinja, sirepo/sim_data/srw.py, sirepo/template/srw.py
3D position and orientation from beamline_orient.dat.
=> Issue/2119 beamline3dReport now uses beamline_orient.dat

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/html/ml-classification.html, sirepo/package_data/static/js/ml.js, sirepo/template/ml.py
@moellep [here is an alpha self extracting sim](https://github.com/radiasoft/sirepo/files/5126331/iris.html.zip) you can use to test the heatplot centering for a 3x3 confusion matrix.
=> Fix #2830. Use heatmap for confusion matrix.

sirepo/package_data/static/html/ml-classification.html, sirepo/package_data/static/js/flash.js, sirepo/package_data/static/js/ml.js, sirepo/package_data/static/json/ml-schema.json, sirepo/package_data/template/ml/classification-base.py.jinja, sirepo/package_data/template/ml/decision-tree.py.jinja, sirepo/package_data/template/ml/knn.py.jinja, sirepo/package_data/template/ml/linear-svc.py.jinja, sirepo/template/ml.py, sirepo/template/opal.py, sirepo/template/template_common.py
This branch is based on issue/2872-decision-tree. Please review and merge PR #2876. Before reviewing this.
=> Fix #2877. Add LinearSVC classifier.

sirepo/package_data/static/html/ml-classification.html, sirepo/package_data/static/js/flash.js, sirepo/package_data/static/js/ml.js, sirepo/package_data/static/json/ml-schema.json, sirepo/package_data/template/ml/classification-base.py.jinja, sirepo/package_data/template/ml/decision-tree.py.jinja, sirepo/package_data/template/ml/knn.py.jinja, sirepo/package_data/template/ml/linear-svc.py.jinja, sirepo/package_data/template/ml/logistic-regression.py.jinja, sirepo/template/ml.py, sirepo/template/opal.py, sirepo/template/template_common.py
This branch is based on issue/2877-svm. Please review and merge PR #2887 before reviewing this.
=> Fix #2888. Add LogisticRegression classifier.

sirepo/package_data/static/html/ml-classification.html, sirepo/package_data/static/js/ml.js, sirepo/package_data/static/json/ml-schema.json, sirepo/package_data/template/ml/decision-tree.py.jinja, sirepo/package_data/template/ml/knn.py.jinja, sirepo/package_data/template/ml/linear-svc.py.jinja, sirepo/package_data/template/ml/logistic-regression.py.jinja, sirepo/template/ml.py
This branch is based on issue/2896-argmin. Merge #2900 before reviewing this.
=> Fix # 2903. Remove dtRegressor. Display dtClassifierClassificationMetricsAnimation.

sirepo/http_reply.py
=> Fix #2869 - return flask.jsonify() for application/json content type 

sirepo/feature_config.py, sirepo/package_data/static/en/landing.html, sirepo/package_data/static/en/particle-accelerators.html, sirepo/package_data/static/en/plans.html, sirepo/package_data/static/en/terms.html, sirepo/package_data/static/en/xray-beamlines.html, sirepo/package_data/static/js/ml.js
Also hide "analysis" app mode until implemented
=> fix #2935 add ML app to production codes

sirepo/package_data/static/js/srw.js, sirepo/package_data/template/srw/beamline_optics.py.jinja, sirepo/package_data/template/srw/parameters.py.jinja, sirepo/template/srw.py, tests/template/srw_generate_data/boron-fiber-crl-with-3-lenses.py, tests/template/srw_generate_data/gaussian-x-ray-beam-through-a-beamline-containing-imperfect-mirrors.py, tests/template/srw_generate_data/mask-example.py, tests/template/srw_generate_data/nsls-ii-chx-beamline.py, tests/template/srw_generate_data/nsls-ii-esm-beamline.py, tests/template/srw_generate_data/nsls-ii-hxn-beamline-ssa-closer.py, tests/template/srw_generate_data/nsls-ii-smi-beamline.py, tests/template/srw_generate_data/nsls-ii-srx-beamline.py, tests/template/srw_generate_data/sample-from-image.py, tests/template/srw_generate_data/srw-all-optics.py, tests/template/srw_generate_data/tabulated-undulator-example.py
=> fix planar mirror orientation and other vtk orientation fixes

sirepo/auth/github.py, sirepo/github_srunit.py, sirepo/server.py
Figured out how authlib works (not easy) and implemented
an authlib integration that does not include flask
=> Fix #2943 eliminated authlib.integrations.flask_client

sirepo/package_data/static/js/radia.js
=> Fix #2959 - beamAxis in appDefaultSimulationValues

sirepo/template/elegant.py
call _sdds_init wherever needed
=> Fix #3077 added _sdds_init

sirepo/package_data/static/html/controls-controls.html, sirepo/package_data/static/js/controls.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/controls-schema.json, sirepo/sim_data/controls.py, sirepo/template/controls.py, sirepo/template/madx.py
@moellep I have some questions. I left comments with them below.
=> WIP: Fix #3088. Add bpm plots as well as twiss and beam commands.

sirepo/package_data/static/js/ml.js, sirepo/package_data/template/ml/scale.py.jinja, sirepo/sim_data/ml.py, sirepo/template/ml.py
- allow multiple alpha columns, convert to encoded if used
- don't require one alpha column for classification
- use column value for label if numeric
- fix file path usage to use sim_data
=> fix issue #3116 ml classification data issues

sirepo/package_data/static/en/landing.html
Code is already in ```_PROD_FOSS_CODES``` so this should be the only change
=> Fix #3155 - added radia to menu

sirepo/package_data/static/en/landing.html, sirepo/package_data/static/en/particle-accelerators.html, sirepo/package_data/static/en/plans.html, sirepo/package_data/static/en/terms.html, sirepo/package_data/static/en/xray-beamlines.html, sirepo/package_data/static/js/ml.js, sirepo/package_data/static/json/ml-schema.json, sirepo/package_data/static/json/schema-common.json, sirepo/package_data/template/ml/scale.py.jinja, sirepo/sim_data/ml.py, sirepo/template/ml.py
- fix #3126 show column reports as scatter plots. Allow selecting x axis column
- fix #3082 show an error "column values are not numeric" if column report encounters NaN
- fix #3133 rename "Machine Learning" app to "Activait"
- fix #3069 improve 6000+ col dataset javascript from 1 minute to < 15 seconds
=> ml: many improvements to column view and selection

tests/template/elegant_import_data/spectrometer1.ele.txt
sirepo.lib no longer mangles filenames.
=> Fix broken tests.

sirepo/template/radia.py
This may have been part of an avenue I removed incompletely and forgot about
=> Fix #3181 - removed g_type param

sirepo/feature_config.py, sirepo/package_data/static/json/shadow-schema.json, sirepo/package_data/template/shadow/beam_statistics.py.jinja, sirepo/package_data/template/shadow/parameters.py.jinja, sirepo/package_data/template/shadow/undulator.py.jinja, sirepo/pkcli/shadow.py, sirepo/template/shadow.py, sirepo/template/srw_shadow_converter.py, tests/template/srw_shadow_converter_data/crl-shadow.json, tests/template/srw_shadow_converter_data/gaussian-shadow.json, tests/template/srw_shadow_converter_data/grating-shadow.json
- calculate undulator sigmas from rays
- added beam statistics report drift divisions field
- added spherical and toroidal mirror to srw->shadow translator
=> fix #3177 and fix #3196 added drift divisions option and mirrors

sirepo/package_data/static/css/srw.css, sirepo/package_data/static/js/sirepo-beamline.js
- replaced javascript positioning code with css
=> fix #3278 beamline digest infinite loop

sirepo/package_data/template/radia/default-data.json, sirepo/package_data/template/radia/examples/undulator.json, sirepo/sim_data/radia.py, sirepo/template/radia.py
Notes:
- fixed various file paths
- solver h5 file is in its own run_dir
- fixed undulator example so kick map actually shows up
=> Fix #3207 radia solve fails

sirepo/package_data/static/js/ml.js
@moellep [here](https://github.com/radiasoft/sirepo/files/5822169/adverts.csv.txt) is a dataset with a large number of cols you can use to test.
=> Fix #3192: paging of datasets with a large number of columns

sirepo/auth/__init__.py, sirepo/auth_db.py, sirepo/db_upgrade.py, sirepo/job_supervisor.py, sirepo/package_data/uwsgi.py.jinja, sirepo/pkcli/admin.py, sirepo/pkcli/roles.py, sirepo/pkcli/service.py, sirepo/server.py, sirepo/srdb.py, sirepo/srunit.py, sirepo/util.py, tests/adm_and_own_jobs_test.py, tests/proprietary_sim_types_test.py, tests/supervisor_purge_free_sims_test.py
Adds a "db_upgrade" concept to keep track of upgrades applied to
the db.
=> Fix #3338: Upgrade to import new FLASH proprietary lib files

sirepo/package_data/static/js/shadow.js, sirepo/package_data/static/json/shadow-schema.json, sirepo/package_data/template/shadow/beam_statistics.py.jinja, sirepo/package_data/template/shadow/parameters.py.jinja, sirepo/package_data/template/shadow/zone_plate.py.jinja, sirepo/template/shadow.py, sirepo/template/srw_shadow_converter.py, tests/template/shadow_generate_data/K5Jl4TGI.txt, tests/template/shadow_generate_data/UWuo7CRU.txt, tests/template/shadow_generate_data/v4jm3q9M.txt
- new shadow zone plate element
- srw zone plate translator
- fix elliptical aperture
- fix autofocus mirrors on beam stats report
=> fix #3341 add shadow zone plate

sirepo/package_data/static/html/silas-crystal.html, sirepo/package_data/static/js/silas.js, sirepo/package_data/static/json/silas-schema.json, sirepo/package_data/template/silas/crystal.py.jinja, sirepo/package_data/template/silas/parameters.py.jinja, sirepo/sim_data/silas.py, sirepo/template/silas.py
- added Crystal tab
- added heat decay profile reports for crystal
- keep crystal width in sync between tabs
- clear reports if crystal width is changed
- renamed Beamline tab to Laser Cavity
=> fix #3363 silas Crystal tab

sirepo/package_data/static/js/sirepo-plotting.js, sirepo/sim_data/srw.py, sirepo/template/srw.py
- This was previously present in a pull request which failed to get merged with master
=> fix #3305 added plot range implementation for SRW

sirepo/package_data/static/html/flash-visualization.html, sirepo/package_data/static/js/flash.js, sirepo/template/flash.py
=> Fix radiasoft/flashcap#4: Show full setup command

sirepo/importer.py, sirepo/job_api.py, sirepo/server.py, sirepo/srschema.py
1. In api_errorLogging log regardless of the exception type
2. Add log statements to util Replies for context when debugging
=> Fix #3425: Improve logging

setup.py, sirepo/package_data/static/html/flash-visualization.html, sirepo/package_data/static/js/flash.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/json/flash-schema.json, sirepo/package_data/template/flash/default-data.json, sirepo/package_data/template/flash/examples/caplaser3d.json, sirepo/package_data/template/flash/examples/caplaserbella.json, sirepo/package_data/template/flash/examples/rtflame.json, sirepo/sim_data/flash.py, sirepo/template/flash.py
Depends on radiasoft/download#159
=> Fix radiasoft/sirepoflash#18: 1D profile plots

sirepo/package_data/static/html/radia-visualization.html, sirepo/package_data/static/js/radia.js, sirepo/package_data/static/json/radia-schema.json, sirepo/package_data/template/radia/examples/dipole.json, sirepo/package_data/template/radia/examples/undulator.json, sirepo/package_data/template/radia/examples/wiggler.json, sirepo/sim_data/radia.py, sirepo/template/radia.py, sirepo/template/template_common.py
Notes:
- As commented in #3474, this geometry is not solvable.  Although we don't know whether any given geometry is solvable, we do know this example is not, so a flag has been added to keep the solver panel from showing
- The solver panel is now up at the top so other panels don't displace it
- This fix also displays Radia errors to the user instead of the unhelpful ```exit(1)```
=> Fix #3474 radia wiggler solve fails

sirepo/package_data/static/js/flash.js, sirepo/package_data/static/json/flash-schema.json, sirepo/package_data/template/flash/examples/caplaser3d.json, sirepo/package_data/template/flash/examples/caplaserbella.json, sirepo/package_data/template/flash/examples/rtflame.json, sirepo/sim_data/flash.py, sirepo/template/flash.py
This moves to using yt to parse the hdf5 output files instead of parsing
them ourselves. In addition it allows specification of an aixs to perform
the slice on. Finally, it allows specifying if limits for the color bar.
=> Fix radiasoft/flashcap#10: use yt for variable animation

sirepo/package_data/static/html/controls-controls.html, sirepo/package_data/static/html/lattice.html, sirepo/package_data/static/js/controls.js, sirepo/package_data/static/js/sirepo-dom.js, sirepo/package_data/static/js/sirepo-lattice.js, sirepo/package_data/static/json/controls-schema.json
Moved webcon specific code out of sirepo-lattice.js and into controls.js
=> Webcon fixes

sirepo/package_data/static/js/flash.js, sirepo/sim_data/flash.py
1. Better parsing of the log to include information prefix with *
2. Show the error in a "well"
=> enhance error message for the setup command

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/schema-common.json
=> Fix #3455: Do not repeat error lines in simulation status

sirepo/html.py, sirepo/package_data/static/en/landing.html, sirepo/package_data/static/en/particle-accelerators.html, sirepo/package_data/static/en/plans.html, sirepo/package_data/static/en/privacy.html, sirepo/package_data/static/en/terms.html, sirepo/package_data/static/en/xray-beamlines.html, sirepo/server.py
@robnagler there are a couple regex changes in here. My skills are improving but please take a close look at them:)
=> Fix #3256: eliminate copied list of apps and list configurable

sirepo/feature_config.py, sirepo/job_supervisor.py, sirepo/package_data/static/html/controls-controls.html, sirepo/package_data/static/js/controls.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/controls-schema.json, sirepo/package_data/template/controls/parameters.py.jinja, sirepo/pkcli/controls.py, sirepo/sim_data/controls.py, sirepo/template/controls.py, test.sh
- Fix #3597: run simulation once after mad-x lattice selection
- Fix #3596: Run simulation once when kicker values are updated 
- Fix #2837: resolve 400 response for some runSimulation requests
=> Webcon get monitor initial positions (on load and kicker value change)

sirepo/template/controls.py
A negative item in a list of beamline items means that the sub-line is
reflected (items are reversed). We were not handling this properly.
=> Fix #3657: Handle reflected sublines when uniquifying beamline.

sirepo/pkcli/job_agent.py
NERSC is working as configured.
=> Fix #3676: enable mpi in dev

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/json/radia-schema.json, sirepo/template/radia.py
Also fixes #3573, #3720, #3722 and eliminates use of get_application_data when downloading field data
=> Fix #3718 radia field integrals broken

sirepo/cookie.py, sirepo/srcontext.py, sirepo/util.py
From looking through the logs it is unclear what exactly caused the error.
These assertions and logging will hopefully narrow down places where we are in a
state we do not expect (ex beleive we are in a request but flask.request is
False).
=> WIP #3727: Add assertions to help diagnose error

sirepo/package_data/static/css/lattice.css, sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-lattice.js, sirepo/package_data/static/js/sirepo.js
- improve drag item position
- refactor modalDialog into a new component
- move selectedItem into latticeService
- improve deepEquals() to do initial === comparison
- combine beamline editor caches into 1 cache
=> fix #3807 drag icon improvements

sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/schema-common.json, sirepo/server.py
Generates this for schema error:
=> Fix #3377 added forbidden api and check in js

sirepo/package_data/static/js/sirepo-lattice.js
- fixed missing element name on delete beamline element confirmation
- raise Error() if an unknown element is requested from the cache
- fixed double-save of simulation when an element is dragged
=> fix #3832 lattice element name in delete confirmation

sirepo/package_data/static/js/srw.js
=> Fix #3864 - renamed numberList to srwNumberList

sirepo/package_data/static/html/srw-source.html, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/template/srw/parameters.py.jinja, sirepo/pkcli/srw.py, sirepo/sim_data/srw.py, sirepo/template/srw.py, tests/template/srw_generate_data/boron-fiber-crl-with-3-lenses.py, tests/template/srw_generate_data/gaussian-x-ray-beam-through-a-beamline-containing-imperfect-mirrors.py, tests/template/srw_generate_data/mask-example.py, tests/template/srw_generate_data/nsls-ii-chx-beamline.py, tests/template/srw_generate_data/nsls-ii-esm-beamline.py, tests/template/srw_generate_data/nsls-ii-hxn-beamline-ssa-closer.py, tests/template/srw_generate_data/nsls-ii-smi-beamline.py, tests/template/srw_generate_data/nsls-ii-srx-beamline.py, tests/template/srw_generate_data/sample-from-image.py, tests/template/srw_generate_data/srw-all-optics.py, tests/template/srw_generate_data/tabulated-undulator-example.py
- added Coherent Modes panel to SRW source page
- On Partially Coherent panel, allow an h5 input file of modes
=> fix #3852 fix #3853 srw coherent mode panel and use on multielectron tab

sirepo/package_data/static/html/raydata-data-source.html, sirepo/package_data/static/js/raydata.js, sirepo/package_data/static/json/raydata-schema.json, sirepo/package_data/template/raydata/examples/mock-analysis.json, sirepo/package_data/template/raydata/parameters.py.jinja, sirepo/sim_data/raydata.py, sirepo/template/raydata.py, sirepo/template/zgoubi_importer.py, sirepo/util.py
This is based on sirepo-3867-analysis-png please review and merge #3889 before reviewing this.
=> Fix radiasoft/raydata#3: User uploads masks

sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/template/shadow/beam_statistics.py.jinja, sirepo/pkcli/shadow.py, sirepo/template/srw.py
- process beam statistics data immediately after simulation
- also added lower limit to SRW grating diffraction order
=> fix #3938 shadow beam statistics report raw data improvements

sirepo/sim_data/__init__.py
=> Fix #3659 radia parameterized dipole

sirepo/package_data/static/js/sirepo-lattice.js
- also fix #3964 fix reverse beamline feature
=> fix #4005 application specific shift-click element behavior

sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/template/srw/README.txt.jinja, sirepo/package_data/template/srw/parameters.py.jinja, sirepo/package_data/template/srw/rsoptExport.sh.jinja, sirepo/package_data/template/srw/rsoptExport.yml.jinja, sirepo/template/srw.py
Notes:
- adds a randomSeed field, along with buttons to generate a seed randomly or based on time (modulo the max value set in the schema)
- fixes #3984 by just putting everything into an hdf5 file. There did not seem to be a reason to separate the data. The shell script and README reflect this change
- fixes #3987, explicitly turning off unused reports
=> Fix #3983 blicon set rnd seed

sirepo/feature_config.py, sirepo/mpi.py, sirepo/package_data/static/js/flash.js, sirepo/package_data/static/json/flash-schema.json, sirepo/pkcli/job_agent.py, sirepo/sim_data/__init__.py, sirepo/sim_data/flash.py, sirepo/srunit.py, sirepo/util.py
- Use output of prepare_simulation to start  codes through sbatch with the proper command
- Get FLASH running on NERSC
=> FLASH on NERSC

sirepo/package_data/static/js/controls.js, sirepo/package_data/static/json/controls-schema.json, sirepo/sim_data/controls.py, sirepo/template/controls.py
Particle plots and monitors now have fixed axes. The editor panel at the very top 'Beamlines' has a panel that lets you change the size of the fixed axes.
=> 4094 fixed aperture plots

sirepo/pkcli/madx.py
now uses the beam command from models.commands
=> fix #4118 madx beam bug

sirepo/package_data/static/js/controls.js, sirepo/package_data/template/controls/parameters.py.jinja, sirepo/pkcli/controls.py, sirepo/pkcli/madx.py, sirepo/template/controls.py
particle distribution now changed by UI inputs
=> 4121 set particle disribution

sirepo/template/controls.py
cases issue is handled now. And loop with enumerate()
=> Fix #4123 upper case target matches upper case madx converted instrument

sirepo/package_data/template/controls/parameters.py.jinja, sirepo/template/controls.py
Optimizer error message shows if all run_sim calls fail and update_and_run fixed to attempt to get readings when is_success.
=> 4124 optimizer error message

sirepo/package_data/static/html/controls-controls.html, sirepo/package_data/static/js/controls.js, sirepo/package_data/static/json/controls-schema.json, sirepo/sim_data/controls.py
Instruments are now in one panel with one editor that adjust axes and colormap.
=> 4116 one panel cross sections

sirepo/package_data/static/html/controls-controls.html, sirepo/package_data/static/js/controls.js, sirepo/template/controls.py
markers are converted to monitors. Four cases handled; markers & monitors, neither markers nor monitors and cases with one but not the other.
Also fixed bug where cross section panel renders even if no instruments
=> 3762 markers as monitors

sirepo/package_data/static/html/controls-controls.html, sirepo/package_data/static/js/controls.js, sirepo/package_data/template/controls/examples/atr-u-and-w-lines.json, sirepo/package_data/template/controls/examples/beamline.json, sirepo/sim_data/controls.py
- fixup for old beamlines with SELECT commands
- moved instrumentAnimationTwiss init to sim_data.controls
- consolidated calls to saveChanges()
=> fix #4146 added fixup for old controls data

sirepo/package_data/static/js/sirepo-plotting.js
adjustZoomToCenter is now called when fully zoomed out.
=> 4153 adjust zoom center

sirepo/package_data/static/html/raydata-analysis.html, sirepo/package_data/static/html/raydata-data-source.html, sirepo/package_data/static/js/raydata.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/raydata-schema.json, sirepo/template/raydata.py
Also, moved to using appFieldEditors with custom type to handle the
scan selection table.
=> Fix radiasoft/raydata#11: user select databroker catalog

sirepo/job_driver/local.py, sirepo/job_driver/sbatch.py, sirepo/job_supervisor.py, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js, tests/job_concurrency1_test.py
4135-pending-resources is based on 2435-run-sim-no-await please review and merge #4187 before reviewing this.
=> fix #4135 pending resources

sirepo/package_data/static/html/elegant-visualization.html, sirepo/package_data/static/js/elegant.js, sirepo/package_data/static/js/sirepo-lattice.js, sirepo/template/elegant.py, sirepo/template/lattice.py
Now multiple run_setup visualizations will have their corresponding lattices.
=> 4062 multiple run setup UI fix

sirepo/package_data/template/silas/parameters.py.jinja
Changes made to silas to correctly instantiate LaserCavity given recent rslaser changes
=> 4212 silas rslaser update

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/json/radia-schema.json, sirepo/package_data/template/radia/examples/dipole.json, sirepo/package_data/template/radia/examples/undulator.json, sirepo/package_data/template/radia/examples/wiggler.json, sirepo/template/radia.py
Also:
- adds an axis path when creating a new undulator
- sets the plotAxis properly
=> Fix #4278 - fixed fieldPaths in examples

setup.py, sirepo/hundli_console.py
Removes deps that are unnecessary. Fixes hundly_console.py to work without yaml (not a Sirepo dep). Removes other deps that were causing problems and unnecesary. Documents deps that are optional.
=> Fix #4318 update myapp and sirepo deps

sirepo/package_data/static/js/srw.js, sirepo/package_data/static/json/srw-schema.json
Now the parameters:
* period
* length
* effective deflecting parameter
Are in the advanced editor panel, and all the others have been moved into the basic editor panel
=> 3977 conspicuous undulator panel

sirepo/package_data/static/js/srw.js
Is there more to it than this?
=> Fix #4332: now macro-electrons

sirepo/template/opal.py, tests/template/madx_converter_data/test4.in, tests/template/madx_converter_data/test4.madx, tests/template/madx_converter_test.py
Drifts are now inserted to fill empty spaces when converting from opal to madx
=> Fix #4262: opal to madx lattice

sirepo/server.py, sirepo/util.py
Now logs message when server is true
=> Fix #3810: flask messages

sirepo/template/radia.py, sirepo/template/template_common.py, sirepo/template/warppba.py
Renamed the param and changed calls
Anything more @robnagler?
=> Fix #4363: rename mpi param

sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/template/srw/parameters.py.jinja, sirepo/template/srw.py
Fields for wm_ns, wm_na, sm_ns, sm_na parameters
=> Fix #2504: select na ns fields

sirepo/template/cloudmc.py, sirepo/template/elegant.py, sirepo/template/flash.py, sirepo/template/genesis.py, sirepo/template/irad.py, sirepo/template/jspec.py, sirepo/template/madx.py, sirepo/template/myapp.py, sirepo/template/opal.py, sirepo/template/radia.py, sirepo/template/rcscon.py, sirepo/template/rs4pi.py, sirepo/template/shadow.py, sirepo/template/silas.py, sirepo/template/synergia.py, sirepo/template/warppba.py, sirepo/template/warpvnd.py, sirepo/template/webcon.py, sirepo/template/zgoubi.py
=> Fix #4428: normalized get_data_file

sirepo/package_data/static/js/flash.js, sirepo/package_data/static/js/sirepo-beamline.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/json/flash-schema.json, sirepo/template/flash.py
- Improved layout on the Parameters tab
- Added module/field search on Parameter tab
- Plotting with multiple sets of x points will not show the plot overlay
because the overlay assumes all plots are on the same x points
- Added 1D "interpolate" option
- 1D profile plot now correctly gives data across different x points
=> 4420 flash 1d reports

sirepo/package_data/static/html/srw-source.html
Move the trajectory and electron beam reports next to each other
=> Fix #3979: trajectory and beam next to each other

sirepo/package_data/static/html/radia-visualization.html, sirepo/package_data/static/js/cloudmc.js, sirepo/package_data/static/js/opal.js, sirepo/package_data/static/js/radia.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-geometry.js, sirepo/package_data/static/js/sirepo-plotting-vtk.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/json/radia-schema.json
Notes: 
- leverages vtkToPNG which is now in plotting-vtk
- cloudmc and opal use the same code and so also support png downloads
- also captures the axes overlay. It takes some manipulation so there may be artifacts
- the coordinate axes now go through the origin. There should probably be a toggle for the user
=> Fix #4444 radia magnet viewer download

sirepo/package_data/static/html/srw-source.html
- also fix report priorities, bumping trajectoryReport priority
=> fix #4465 move trajectory report beneath undulator editor

sirepo/package_data/static/js/srw.js
The undulator seems to be auto updating correctly now
=> Fix #4448: undulator length auto updates

sirepo/package_data/static/js/srw.js, sirepo/package_data/static/json/srw-schema.json
=> Fix #4500: missing undulator field updates

sirepo/package_data/static/js/radia.js
=> Fix #4525 - wantButtons not set

sirepo/package_data/static/css/sirepo.css, sirepo/package_data/static/html/cloudmc-geometry.html, sirepo/package_data/static/js/cloudmc.js, sirepo/package_data/static/json/cloudmc-schema.json, sirepo/template/cloudmc.py
Added cloudmc material editor.
=> 4517 cloudmc materials

test.sh
radiasoft/container-sirepo-ci#4
=> fix container-sirepo-ci#4: Add karma globally and fix test.sh

.github/workflows/ci-pull-request.yml, sirepo/http_request.py
Depends on https://github.com/radiasoft/download/pull/226
Depends on https://github.com/radiasoft/download/issues/234
=> fix #4461: add ci-pull-request github action

sirepo/package_data/static/json/flash-schema.json, sirepo/sim_data/flash.py
- update MGD text to display "Multigroup Diffusion", fix #4557 
- show setup or compile source of Setup and Compile error message, fix #4558
=> 4557 flash mgd text

sirepo/package_data/static/js/flash.js, sirepo/package_data/template/flash/init-zip.py.jinja
No shows an error message if a zip file which is missing Config or flash.par at the root level of the problem file zip archive.
=> fix #4573 and fix #4546 show error if missing flash.par

sirepo/sim_data/flash.py
=> fix #4593 flash fmt

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/json/radia-schema.json
Previously the plot was being updated only if the user selected a new path, not on changes to the current path.
This also amends the current density units
=> Fix #4685 radia update field on path

sirepo/exporter.py, sirepo/pkcli/service.py
The option for python_source_for_model to export multiple files for was added to the exporter
=> Allow multiple output files in an app export

sirepo/pkcli/service.py, sirepo/server.py
Home page redirect goes to landing
Add server.cfg.react_sim_types
=> Fix #4724 run npm install if react not installed

sirepo/package_data/static/js/sirepo-lattice.js, sirepo/template/template_common.py
Apps can define custom help text on the beamline editor panel.
=> 4773 beamline help text

sirepo/package_data/static/json/cloudmc-schema.json, sirepo/package_data/template/cloudmc/parameters.py.jinja
https://docs.openmc.org/en/stable/usersguide/settings.html?highlight=photon%20transport#photon-transport
=> Fix radiasoft/prop22_cloudmc#18: add photon_transport option

sirepo/package_data/static/json/radia-schema.json, sirepo/template/radia.py
This also cleans up `_save_kick_map_sdds()` and removes the download as text option, which was never implemented and is of unclear importance.
=> Fix #4782 kickmap error

sirepo/package_data/static/json/cloudmc-schema.json, sirepo/package_data/template/cloudmc/parameters.py.jinja, sirepo/template/cloudmc.py
fix #4795 angular distribution corrected
- also implement EnergyFilter, EnergyOutFilter, ParticleFilter code generation
=> 4795 angular distribution

sirepo/package_data/static/json/srw-schema.json, sirepo/package_data/template/srw/parameters.py.jinja, sirepo/template/srw.py, tests/template/srw_shadow_data/to_srw.out/srw.json, tests/template/srw_shadow_data/to_srw_mirror.out/srw.json, tests/template/srw_shadow_data/to_srw_undulator.out/srw.json
The script runs without error, but I am not sure how to tell whether the results reflect the setting.
=> Fix #4853 ml export characteristic

sirepo/feature_config.py, sirepo/sim_data/raydata.py, sirepo/template/raydata.py
depends on https://github.com/radiasoft/raydata/pull/25
=> fix raydata#24: run analysis notebook and display queued scans

sirepo/package_data/static/js/srw.js
=> Fix #4596: coherent modes on nersc

sirepo/package_data/static/js/sirepo.js
=> Fix #4777: sirepo in title bar

sirepo/package_data/static/js/radia.js
=> Fix #4705 - disabled type field

sirepo/numpy.py, sirepo/package_data/static/js/activait.js, sirepo/package_data/template/activait/scale.py.jinja, sirepo/sim_data/activait.py, sirepo/template/activait.py
Notes:
- Now using a factory to build various DataReader classes
- The data_path param moved to the constructor
- The csv read loop in `sirepo.numpy.py` is now part of the DataReader
- Removed partition plots for image data
=> Fix #4883 hdf5 data loader

sirepo/sim_data/activait.py
- nest sub-methods within _fixup_neural_net()
=> fix #4911 correct activate fixup for dropoutRate fields

setup.py
@e-carlin wait for tests to run just in case.
=> Fix #4952 pyIsEmail rename seems unintentional

sirepo/package_data/static/js/sirepo-lattice.js, sirepo/template/code_variable.py
- guard against invalid rpnVariable value in code generator and UI
- fix bug in rpn editor which would allow an invalid row to be added
=> fix #4935 invalid variable entry

sirepo/package_data/static/html/activait-data.html, sirepo/package_data/static/js/activait.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/static/json/activait-schema.json, sirepo/template/activait.py
Now the data tab has a image sample viewer with 5 sets of 25 images to scroll through
=> Fix #4922: cifar image samples

sirepo/package_data/static/js/controls.js, sirepo/sim_data/controls.py
fix #4961 include monitor position log file with controls export
=> 4961 controls monitor file

sirepo/modules.py
See also https://github.com/radiasoft/sirepo/issues/5007
=> Fix #5006 supervisor only needs auth_db

sirepo/package_data/static/js/sirepo-plotting-vtk.js
This also resizes the workspace if objects are dragged partially outside it
=> Fix #4984 - replot after drawing shapes

etc/run-server.sh, etc/run-supervisor.sh, sirepo/auth/__init__.py, sirepo/modules.py, sirepo/pkcli/job_agent.py
- Changed run-supervisor/server.sh to use another run directory to provoke bugs.
- job_agent does not need to start a quest
=> Fix #5017 job_agent needs to initialize sirepo.auth

sirepo/package_data/static/js/raydata.js
I've tried and haven't been able to recreate the super long loading time that happened during the demo. The longest loading time I'm seeing right now is about 30 seconds.
see comment on radiasoft/raydata#30
=> fix radiasoft/raydata#30: bug fixes

sirepo/template/srw.py
The "private" `_export_rsopt_config` does the work now
=> Fix #5038 - removed function

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/json/radia-schema.json, sirepo/package_data/template/radia/geometryReport.py.jinja, sirepo/template/radia.py
Notes:
- If the final point loaded from the file is the same as the first, it seems to confuse Radia. This removes it
- Also fixes a couple of random bugs
- Attaching a couple of files to test with
[Fillet Points.csv](https://github.com/radiasoft/sirepo/files/9855676/Fillet.Points.csv)
[quad_pole2.csv](https://github.com/radiasoft/sirepo/files/9855677/quad_pole2.csv)
=> Fix #4966 radia point table error

sirepo/package_data/static/js/srw.js, sirepo/template/srw.py
Error is thrown when coherent modes animation has too few cores
=> Fix #4942: coherent modes errors

sirepo/package_data/static/js/radia.js
Lots of small changes in an effort to clean up this file
=> Fix #5067 - cleanup

sirepo/template/activait.py
New layers added for model archive imports:
GlobalAveragePooling2D
GaussianNoise
GaussianDropout
AlphaDropout
SeparableConv2D
AveragePooling2D
UpSampling2D
ZeroPadding2D
=> Fix #5057: more load model layers support

sirepo/package_data/static/html/activait-regression.html, sirepo/package_data/static/js/activait.js, sirepo/package_data/static/js/srw.js, sirepo/package_data/template/activait/train.py.jinja, sirepo/template/activait.py, tests/template/ml_network_data/net.out/net.py, tests/template/ml_network_data/net1.out/net.py, tests/template/ml_network_data/net2.out/net.py, tests/template/ml_network_data/net3.out/net.py, tests/template/ml_network_data/net4.out/net.py
Both weighted and unweighted models are now saved and links for download provided in UI
=> Fix #4908: export h5 models

sirepo/package_data/static/html/radia-source.html
=> Fix #5112 - removed ng-show

sirepo/template/activait.py
Download data files works now. 
Some of the files arent written in .csv format so I added a step that does so
=> Fix #3434: activait download data file

sirepo/template/radia_util.py
=> Fix #5185 - clone transform error

sirepo/template/radia_util.py
=> Fix #5188 - fixed math

sirepo/package_data/static/html/activait-analysis.html, sirepo/package_data/static/js/activait.js
Removed code that was doing nothing
The FFT option on the subplots doesn't seem to work on master.
=> Fix #5201: remove cruft

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-utils.js, sirepo/package_data/static/js/warpvnd.js
Also fixed radia to use it when adding vertices
=> Fix #5190 - largePush to handle big arrays

sirepo/package_data/static/js/activait.js, sirepo/package_data/static/js/shadow.js, sirepo/package_data/static/js/silas.js, sirepo/package_data/static/js/srw.js, sirepo/template/activait.py, sirepo/template/shadow.py, sirepo/template/silas.py, sirepo/template/srw.py
=> Fix #5202: rename stateful_compute_compute_column_info to stateful_compute_column_info

sirepo/package_data/static/js/sirepo-plotting-vtk.js
`drawShapes` disables zoom on objects
=> Fix #5161 radia double click

react/src/component/app.js, react/src/component/simbrowser.js, react/src/hook/stopwatch.ts, react/src/layout/columnbreak.tsx, react/src/layout/form.tsx, react/src/layout/input/boolean.tsx, react/src/layout/layouts.ts, react/src/layout/report.tsx
- show HTML title as "appName - Sirepo"
- format elapsed time as (days) HH:MM:SS
- show/hide form fields
- larger boolean checkbox element
- add ColumnBreakLayout
- show progress bar at 100% when 0% is completed
=> fix #5267 react improvements

sirepo/package_data/template/radia/geometryReport.py.jinja
Also changed those lists to tuples
=> Fix #5312 - extrudedPoints was excluded from lists

react/src/component/app.scss, react/src/component/login/login.scss, react/src/component/login/login.tsx, react/src/component/reusable/navbar.scss, react/src/layout/input/number.tsx, react/src/layout/report.tsx, sirepo/package_data/static/react-json/jspec-schema.json
- format numeric input fields in scientific notation if < 0.001 or > 10000
- numeric input fields align right
- add singleFrameAnimation config option to manual plots so animation control can be hidden
- improve animation buttons UI
=> fix #5321 minor react improvements

sirepo/package_data/static/js/radia.js
Notes:
- Added a show/hide caret
- Changed fields to plain text since they are uneditable
=> Fix #5330 radia hide point table

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/js/sirepo-plotting-vtk.js, sirepo/package_data/static/js/sirepo.js
Main issue here was to redraw the shapes once the new center values are saved. Some duplicated code here but it's fine in the short term (but see https://github.com/radiasoft/sirepo/issues/5280#issue-1500983276).
=> Fix #5329 radia extruded center

sirepo/package_data/static/js/radia.js
Was returning a function, not calling it!
=> Fix #5354 - updateShapes

sirepo/auth_db/__init__.py
Fix #5390 added auth_db.sqlite_timeout=20
=> Fix #5392 audited session locking, no long locks

sirepo/template/radia.py
Added qcall. Also fixed unrelated errors with some numpy arrays that needed to be listified
=> Fix #5424 radia new undulator fails

sirepo/package_data/static/js/sirepo-components.js
Need to ensure the delegate exists before responding to the message. Tested radia and cloudmc
=> Fix #5483 - alpha slider error

sirepo/package_data/static/js/sirepo-plotting-vtk.js
Made this configurable, defaulting to "not nice". radia might be better with it on...
=> Fix #5511 avoid nice vtk axes

sirepo/package_data/template/srw/parameters.py.jinja
Use rs_type in place of simulation.sourceType when generating code
=> fix #5527 tabulated undulator source in idealized mode

etc/run-react-build.sh, react/package-lock.json, react/src/component/app.tsx, react/src/component/login/email.tsx, react/src/component/login/guest.tsx, react/src/component/login/login.tsx, react/src/data/appwrapper.ts, react/src/layout/navbar.tsx, sirepo/server.py
This works until it wants to load a simulation. @garsuga please look at 
- Todo https://github.com/radiasoft/sirepo/issues/5544
- Todo https://github.com/radiasoft/sirepo/issues/5546
- Fixed #5543 do not use /react
=> 20230307 etc/run-react-build.sh fixes

react/src/component/simulation.tsx, react/src/layout/arrange/column.tsx, react/src/layout/form.tsx, react/src/layout/layouts.ts, react/src/layout/multipanel.tsx, react/src/utility/component.ts, sirepo/package_data/static/react-json/common-schema.json
- Download python source link text now configurable by application
- Added simple Column layout for use by mulitipanel
- Multipanel now shows a download PNG button
- FieldList layout now has an option shown and heading config
=> fix #5462 multipanel as png

sirepo/template/code_variable.py, sirepo/template/template_common.py
Fixes issue with rendering a lattice report after import.
Fixes code variable stateful_compute_recompute_rpn_cache_values() redefinition.
Fixes bug with stateful_compute_validate_rpn_delete migration from get_application_data().
=> fix #5562 fix #5563 fix #5564 lattice and code variable bugs

sirepo/package_data/static/js/activait.js
Split method hidden if image data now.
=> Fix #5383: hide manual partition for image

sirepo/template/srw.py
Now wont log errors associated with bad inputs into grating
=> Fix #5420: compute pgm exception

sirepo/package_data/template/srw/parameters.py.jinja, sirepo/template/srw.py, tests/template/srw_generate_data/boron-fiber-crl-with-3-lenses.py, tests/template/srw_generate_data/gaussian-x-ray-beam-through-a-beamline-containing-imperfect-mirrors.py, tests/template/srw_generate_data/mask-example.py, tests/template/srw_generate_data/nsls-ii-chx-beamline.py, tests/template/srw_generate_data/nsls-ii-esm-beamline.py, tests/template/srw_generate_data/nsls-ii-hxn-beamline-ssa-closer.py, tests/template/srw_generate_data/nsls-ii-smi-beamline.py, tests/template/srw_generate_data/nsls-ii-srx-beamline.py, tests/template/srw_generate_data/sample-from-image.py, tests/template/srw_generate_data/srw-all-optics.py, tests/template/srw_generate_data/tabulated-undulator-example.py
When export from cogwheel: `v.wm = False`. When exported from the Partially Coherent tab: `v.wm = True`
=> Fix #5408: multiElectronAnimation export improve

sirepo/package_data/static/json/srw-schema.json, sirepo/template/srw_shadow.py, tests/template/srw_generate_data/nsls-ii-esm-beamline.py, tests/template/srw_generate_data/srw-all-optics.py, tests/template/srw_shadow_data/to_shadow_crl.out/shadow.json, tests/template/srw_shadow_data/to_shadow_gauss.out/shadow.json, tests/template/srw_shadow_data/to_shadow_grating.out/shadow.json
Negative diffraction order allowed now
=> Fix #5508: remove min on diffractionOrder

sirepo/package_data/template/radia/radia_export.py.jinja
Replaced PKDict with **transform
=> Fix #5589 - use kwargs

sirepo/package_data/static/js/radia.js
The offending function should never have been invoked since it is used to make 2d shapes that do not even appear for parameterized magnets.
=> Fix #5652 radia undulator design tab

sirepo/job_api.py, sirepo/package_data/static/js/sirepo.js
- refactored _request_api() args
- cruft: beginSession in sirepo.js
=> Fix #5660 beginSession starts task in tornado

sirepo/sim_data/silas.py, sirepo/template/silas.py
- also fixes float numeric errors on drift elements
=> fix #5666 check that crystal.n0 exists before access

sirepo/package_data/static/js/activait.js, sirepo/template/activait.py
Now can import Reshape layers and will get UI error if user tries to import unsupported error
=> Fix #5769: reshape import

sirepo/package_data/static/js/raydata.js, sirepo/raydata/scan_monitor.py
depends on https://github.com/radiasoft/raydata/pull/90
=> fix raydata#89: csx workflow

sirepo/db_upgrade.py, tests/db_upgrade_data/auth.txt
Update users flash.tar.gz because it contains an update https://github.com/radiasoft/download/pull/479
=> Fix #5905: db_upgrade to deploy flash update

sirepo/package_data/static/js/epicsllrf.js, sirepo/template/epicsllrf.py
Error message for user when pvput fails
=> Fix #5919: pvput should error

sirepo/package_data/static/json/omega-schema.json, sirepo/package_data/static/react-json/omega-schema.json, sirepo/package_data/template/omega/parameters.py.jinja, sirepo/pkcli/genesis.py, sirepo/template/genesis.py, sirepo/template/omega.py
- added default values for simWorkflow
- improved layouts
- improved genesis error handling
=> fix #5965 omega fixes

sirepo/package_data/static/json/radia-schema.json, sirepo/template/radia_util.py
This adds the center point to the cut point if the user sets the corresponding flag
=> Fix #5974 radia local cut plane

sirepo/sim_data/radia.py
=> Fix #6125 - added stl files to _lib_file_basenames

sirepo/package_data/static/js/silas.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/silas-schema.json, sirepo/package_data/template/silas/crystal.py.jinja, sirepo/package_data/template/silas/examples/bella.json, sirepo/template/silas.py
Analytical and Fenics solves for the crystal simulation
=> Fix #6178: thermal crystal sim updates

sirepo/package_data/static/js/sirepo-plotting-vtk.js
I noticed that no invocations of showSide supply the "direction" parameter, so it's gone.
=> Fix #6241 3d axis toggle

sirepo/package_data/static/js/cloudmc.js
Also adds a tooltip to match the panel caret
=> Fix #6301 - flipped caret

sirepo/package_data/static/js/cloudmc.js, sirepo/template/cloudmc.py
2D slices now match openmc-plotter
=> fix #6323 fix slice position and ui image to display alignment

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo-plotting-vtk.js, sirepo/package_data/static/json/radia-schema.json
Notes:
- Show/hide was not being handled due to panelState missing from $scope
- Added code to redraw axes properly after show/hide
- Removed fullscreen - arranging the controls along with the magnet viewer is complicated enough to  have its own issue (if necessary)
=> Fix #4806 radia magnet viewer window

sirepo/package_data/static/js/epicsllrf.js, sirepo/template/epicsllrf.py
depends on radiasoft/pykern/pull/398
=> fix #6290 use analysisJob for polling and pkio module for file compare

sirepo/package_data/static/js/sirepo.js, sirepo/package_data/template/srw/brilliance.py.jinja
Fix #6351 brilliance.py.jinja incorrect srwpy import
=> Fix #6250 added SIREPO.traceWS and better logging

sirepo/package_data/static/html/genesis-visualization.html, sirepo/template/genesis.py
@gurhar1133 please give this PR a test. Here is a good time-dependent simulation to try on dev:
https://www.sirepo.com/genesis#/source/n8RAOs28
=> fix #6448 time dependent page-able final plots

sirepo/package_data/static/js/raydata.js, sirepo/package_data/static/js/sirepo-components.js, tests/karma/utilities_test.js
- added scanCellValue directive which formats json and truncates/expands large items
- always show "View Output" button, possibly disabled
- added utilities objectToText() and trimText()
=> fix #6424 scan table improvements

sirepo/package_data/static/css/raydata.css, sirepo/package_data/static/html/raydata-analysis-queue.html, sirepo/package_data/static/js/raydata.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/raydata-schema.json, sirepo/raydata/scan_monitor.py
- also fix #6256 show error message if start/stop is missing or invalid
- minor method refactoring
=> fix #6436 limit paging to scan page count

sirepo/package_data/static/js/cloudmc.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/package_data/static/json/cloudmc-schema.json, sirepo/template/cloudmc.py
- also hide 2d axes choices for low resolution dimensions
=> fix #6331 preserve zoom unless heatmap axes change

sirepo/package_data/static/js/flash.js, sirepo/sim_data/flash.py, sirepo/template/flash_parser.py, tests/template/flash_parser_data/setup.json, tests/template/flash_parser_data/setup/setup_datafiles, tests/template/flash_parser_data/setup/setup_params, tests/template/flash_parser_data/setup/setup_vars, tests/template/flash_parser_test.py
- also fixes a sim_db_file problem when running the LaserSlab example
=> fix #6519 fixed bug in flash valid value parsing

sirepo/package_data/static/js/raydata.js, sirepo/package_data/static/json/raydata-schema.json, sirepo/raydata/scan_monitor.py
- also fix #6434 add search help text
=> fix #6438 cache scan table data when navigating between tabs

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/json/radia-schema.json, sirepo/sim_data/radia.py
For simplicity, this just adds an upper limit (20 for now) to the number of points and adds a tooltip, plus a fixup. The simulation that precipitated this change loads correctly but slowly at the max limit.
=> Fix #6563 radia field map point limit

sirepo/package_data/static/html/cloudmc-visualization.html, sirepo/package_data/static/js/cloudmc.js, sirepo/package_data/static/json/cloudmc-schema.json
Moved tally controls to a side panel which auto-updates on changes.
=> for #6231 add tally settings side panel

sirepo/package_data/static/json/radia-schema.json
Tested the examples - they behave as expected. It's just the labels that needed switching
=> Fix #6556 - swapped labels

sirepo/package_data/static/js/sirepo-components.js
[companion issue](https://github.com/radiasoft/rsiviz/issues/244)
=> Fix #6570: fileupload dialog no exit while uploading

sirepo/package_data/static/js/radia.js, sirepo/package_data/static/json/radia-schema.json, sirepo/template/radia.py
Notes:
- Adds rpnVariables to `_build_shape_points()`
- Runs `update_geom_from*` on evaluated models
- Adds type field to parameterized models
- Also partially fixes #6592
=> Fix #6603 radia stemmed scripted

sirepo/package_data/static/js/cloudmc.js, sirepo/template/cloudmc.py
Also for #6505 guard against missing run.log on nersc
=> fix #6633 fix missing html type on delete button

sirepo/package_data/static/html/activait-regression.html, sirepo/package_data/static/js/activait.js, sirepo/package_data/static/json/activait-schema.json, sirepo/pkcli/activait.py, sirepo/template/activait.py
Also found a bug in _histograp_plot(). It returns string data which messes with the y domain of the plots since `'80' < '9' == true` in js
=> Fix #6721: improve dice plot

sirepo/package_data/static/js/cloudmc.js
Interesting that parseFloat(<array>) returns the first value...
=> Fix #6849 - display values as array when needed

sirepo/package_data/static/js/cloudmc.js
This moves the label to the plot title and the associated code to the `geometry2d` directive
=> Fix #6844 cloudmc energy filter label

sirepo/package_data/static/html/activait-comparison.html, sirepo/package_data/static/html/activait-data.html, sirepo/package_data/static/html/activait-regression.html, sirepo/package_data/static/js/activait.js, sirepo/package_data/static/json/activait-schema.json, sirepo/template/activait.py
Image to image model comparison. Used pets dataset to test this one
=> Fix #6722: compare model outputs

container-conf/build.sh, pyproject.toml
Fix #6965 renamed SIREPO_COMMIT to SIREPO_BRANCH
=> Fix #6966 added tool.setuptools.package-data.sirepo to pyproject.toml

sirepo/job_supervisor.py
__db_restore was too much. It reset the computeJobSerial which meant the supervisor and gui were out of sync. Instead just set the status to MISSING. This let's the runStatus come in, pick up _sr_exception_in_run and the the user will be prompted to log in.
The job status could be more descriptive. But, MISSING is reasonable because the user clicked run which means they no longer care about the existing run simulation status.
@robnagler I'm going to work on fixing the login flow in https://github.com/radiasoft/sirepo/issues/7008. I want to get a fix in for [cancel](https://github.com/radiasoft/sirepo/issues/6972) before that work.
=> Fix #6981: fix computeJobSerial mismatch when doing sbatch login

sirepo/auth/__init__.py, sirepo/srunit.py, sirepo/uri_router.py
fix #6394: Add support for srunit logging in uri_router
fix #6565: log api early in request
=> fix #6394: Add support for srunit logging in uri_router

etc/run-supervisor.sh, sirepo/package_data/static/js/sirepo-components.js
Add sbatchLoginService to $scope so it can be queried for showSbatchOptions.
Also, fix etc/run-supervisor.sh defaulting of host to localhost.
=> Fix #7115: Display sbatch fields (cores, hours, etc)

sirepo/package_data/template/openmc/examples/zpre.json, sirepo/template/openmc.py
- also fix deprecated warning in openmc python
=> fix #7195 new source constraints for ZPRE example

sirepo/package_data/static/css/sirepo-dark.css, sirepo/package_data/static/js/raydata.js, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js
- also allow save button text to be overridden per modelName
- added DateTimePicker, PresetTimePicker, and OptionalFloat as standard types
=> fix #7244 move common raydata components to sirepo-component.js

sirepo/package_data/static/js/sirepo-components.js
- also add optional viewName attribute to the reportPanel directive
=> fix #7249 safari datetime-local input layout improvement

sirepo/package_data/static/js/raydata.js, sirepo/raydata/analysis_driver/__init__.py, sirepo/raydata/analysis_driver/chx.py, sirepo/raydata/scan_monitor.py
Create the concept of "elegible scan" that tests whether the fields we need are present.
Also cleanup some cruft.
=> Fix radiasoft/raydata#164: handle chx scans without cycle in start doc

sirepo/auth/__init__.py, sirepo/auth_role.py, sirepo/package_data/static/js/sirepo.js, sirepo/package_data/static/json/schema-common.json
We just use premium and enterprise was broken in a few places (ex sbatchLogin being just for premium).
=> Fix #7418: Remove role enterprise

sirepo/package_data/static/html/heatplot.html, sirepo/package_data/static/html/openmc-geometry.html, sirepo/package_data/static/html/openmc-visualization.html, sirepo/package_data/static/js/openmc.js, sirepo/package_data/static/js/sirepo-plotting.js, sirepo/sim_data/openmc.py, sirepo/template/openmc.py, tests/karma/plotAxis_test.js
- also fix #7475 allow STP simulation to be shared and exported
=> fix #7476 energy selection in all planes

sirepo/auth/email.py, sirepo/package_data/static/html/adm-roles.html, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/json/schema-common.json
- Default view shows active subscriptions sorted by email address
- Selecting "Show all rows" will show all users in the database
- Sorting/search not implemented
=> fix #7505 simple adm user view

etc/run.sh, sirepo/uri_router.py
- etc/run.sh supports nginx_proxy
=> Fix #7532 only get port from socket, rely on remote_ip always

sirepo/pkcli/job_agent.py, tests/sbatch_test.py
- Fix #2195 remove pid file only if it is the same process and only remove in start_sbatch (extra check was incorrect)
- Fix #7557 sbatch TIMEOUT is job.CANCEL
=> Fix #6810 job_agent: after 10 retries, give up trying to connect

sirepo/auth/__init__.py, sirepo/auth/email.py, sirepo/auth_role_moderation.py, sirepo/feature_config.py, sirepo/package_data/static/js/sirepo-components.js, sirepo/package_data/static/js/sirepo.js
@robnagler I'm not sure if this is the best way to share the code between auth.login and auth_role_moderation.
=> fix #7585 add feature_config is_moderated
